package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	genNotice = "<!-- Generated by `go generate ./...` (internal/coveragegen). Do not edit by hand. -->"

	dirPerm  = 0o755 // generated docs directories
	filePerm = 0o644 // generated docs files
	twoCols  = 2     // two-column tables (Provider/Exposed as, Operation/Description)
)

func render(root string, services []*Service) error {
	outDir := filepath.Join(root, "docs", "coverage")
	if err := os.MkdirAll(filepath.Join(outDir, "nongoals"), dirPerm); err != nil {
		return err
	}

	if err := writeFile(filepath.Join(outDir, "README.md"), renderIndex(services)); err != nil {
		return err
	}

	for _, svc := range services {
		page := renderService(outDir, svc)
		if err := writeFile(filepath.Join(outDir, svc.Name+".md"), page); err != nil {
			return err
		}
	}

	if err := writeJSON(filepath.Join(outDir, "coverage.json"), services); err != nil {
		return err
	}

	return writeFile(filepath.Join(root, "llms-full.txt"), renderLLMSFull(services))
}

// renderLLMSFull emits a single self-contained plain-text capability dump for
// agents to ingest in one fetch (the llms-full.txt convention): every service,
// the native name per provider, and every operation.
func renderLLMSFull(services []*Service) string {
	var b strings.Builder

	fmt.Fprintln(&b, "# cloudemu capability manifest")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Generated from the driver interfaces by `go generate ./...`; do not edit by hand.")
	fmt.Fprintln(&b, "Every operation below is a method the code declares. Structured form: docs/coverage/coverage.json.")
	fmt.Fprintln(&b)

	for _, svc := range services {
		fmt.Fprintf(&b, "## %s (driver.%s)\n", svc.Name, svc.Interface)
		fmt.Fprintf(&b, "providers: %s\n", providerLine(svc))

		ops := make([]string, len(svc.Operations))
		for i, op := range svc.Operations {
			ops[i] = op.Name
		}

		fmt.Fprintf(&b, "operations (%d): %s\n\n", len(ops), strings.Join(ops, ", "))
	}

	return b.String()
}

func providerLine(svc *Service) string {
	parts := make([]string, 0, len(providerOrder))

	for i, prov := range providerOrder {
		if native := svc.Providers[prov]; native != "" {
			parts = append(parts, providerTitles()[i]+"="+native)
		}
	}

	if len(parts) == 0 {
		return "(none implemented)"
	}

	return strings.Join(parts, ", ")
}

func renderIndex(services []*Service) string {
	var b strings.Builder

	fmt.Fprintln(&b, genNotice)
	fmt.Fprintln(&b, "# Capability coverage")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Every service cloudemu emulates and the native name each provider exposes it under.")
	fmt.Fprintln(&b, "Each row links to the full, operation-level list. This page is generated from the")
	fmt.Fprintln(&b, "driver interfaces in `services/*/driver`, so it cannot promise a capability the code")
	fmt.Fprintln(&b, "does not implement. A machine-readable version lives in [`coverage.json`](./coverage.json).")
	fmt.Fprintln(&b)

	header := append([]string{"Service"}, providerTitles()...)
	header = append(header, "Operations")
	fmt.Fprintln(&b, tableRow(header))
	fmt.Fprintln(&b, tableRule(len(header)))

	for _, svc := range services {
		cells := make([]string, 0, len(providerOrder)+twoCols)
		cells = append(cells, fmt.Sprintf("[%s](./%s.md)", svc.Name, svc.Name))

		for _, prov := range providerOrder {
			cells = append(cells, orDash(svc.Providers[prov]))
		}

		cells = append(cells, fmt.Sprintf("%d", len(svc.Operations)))
		fmt.Fprintln(&b, tableRow(cells))
	}

	renderProviderNotes(&b, services)

	return b.String()
}

// renderProviderNotes flags any provider whose services are all unimplemented,
// so an all-dash column reads as "foundation only" rather than "not a provider".
func renderProviderNotes(b *strings.Builder, services []*Service) {
	for i, prov := range providerOrder {
		implemented := 0

		for _, svc := range services {
			if svc.Providers[prov] != "" {
				implemented++
			}
		}

		if implemented == 0 {
			fmt.Fprintf(b, "\n> **%s**: foundation only — the provider scaffold exists "+
				"(identity, IDs, wire layer) but no services are implemented yet, so every "+
				"row above is `—`.\n", providerTitles()[i])
		}
	}
}

func renderService(outDir string, svc *Service) string {
	var b strings.Builder

	fmt.Fprintln(&b, genNotice)
	fmt.Fprintf(&b, "# %s\n\n", svc.Name)
	fmt.Fprintf(&b, "Portable interface: `driver.%s`\n\n", svc.Interface)
	renderProviderTable(&b, svc)
	fmt.Fprintf(&b, "## Operations (%d)\n\n", len(svc.Operations))
	renderOpTable(&b, svc.Operations)

	if len(svc.Capabilities) > 0 {
		fmt.Fprintln(&b, "## Optional capabilities")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "Discovered by type assertion; only some providers implement these.")
		fmt.Fprintln(&b)

		for _, cap := range svc.Capabilities {
			fmt.Fprintf(&b, "### %s\n\n", cap.Name)

			if cap.Doc != "" {
				fmt.Fprintf(&b, "%s\n\n", cap.Doc)
			}

			renderOpTable(&b, cap.Operations)
		}
	}

	fmt.Fprintln(&b, "## Not in scope")
	fmt.Fprintln(&b)
	fmt.Fprint(&b, nonGoals(outDir, svc.Name))

	return b.String()
}

func renderProviderTable(b *strings.Builder, svc *Service) {
	fmt.Fprintln(b, tableRow([]string{"Provider", "Exposed as"}))
	fmt.Fprintln(b, tableRule(twoCols))

	for i, prov := range providerOrder {
		fmt.Fprintln(b, tableRow([]string{providerTitles()[i], orDash(svc.Providers[prov])}))
	}

	fmt.Fprintln(b)
}

func renderOpTable(b *strings.Builder, ops []Operation) {
	fmt.Fprintln(b, tableRow([]string{"Operation", "Description"}))
	fmt.Fprintln(b, tableRule(twoCols))

	for _, op := range ops {
		fmt.Fprintln(b, tableRow([]string{"`" + op.Name + "`", op.Doc}))
	}

	fmt.Fprintln(b)
}

// nonGoals inlines a hand-maintained fragment if present, else a default line.
func nonGoals(outDir, service string) string {
	data, err := os.ReadFile(filepath.Join(outDir, "nongoals", service+".md"))
	if err == nil && strings.TrimSpace(string(data)) != "" {
		return strings.TrimRight(string(data), "\n") + "\n"
	}

	return "_Not documented yet. See the [emulator boundary](../README.md) for cloudemu-wide non-goals._\n"
}

func writeJSON(path string, services []*Service) error {
	data, err := json.MarshalIndent(services, "", "  ")
	if err != nil {
		return err
	}

	return writeFile(path, string(data)+"\n")
}

func writeFile(path, content string) error {
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}

	return os.WriteFile(path, []byte(content), filePerm)
}

func providerTitles() []string {
	titles := map[string]string{"aws": "AWS", "azure": "Azure", "gcp": "GCP", "oci": "OCI"}
	out := make([]string, len(providerOrder))

	for i, p := range providerOrder {
		if t, ok := titles[p]; ok {
			out[i] = t
		} else {
			out[i] = strings.ToUpper(p)
		}
	}

	return out
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}

	return s
}

func tableRow(cells []string) string { return "| " + strings.Join(cells, " | ") + " |" }

func tableRule(n int) string {
	parts := make([]string, n)
	for i := range parts {
		parts[i] = "---"
	}

	return "| " + strings.Join(parts, " | ") + " |"
}
