package keyvault

import (
	"context"
	"crypto/x509"
	"testing"

	"github.com/stackshy/cloudemu/v2/errors"
	"github.com/stackshy/cloudemu/v2/services/secrets/driver"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func createParams() driver.KVCreateCertificateParams {
	return driver.KVCreateCertificateParams{
		Subject:     "CN=mycert.example.com",
		DNSNames:    []string{"mycert.example.com"},
		ContentType: "application/x-pkcs12",
		Attributes:  driver.KVAttributes{Enabled: true},
		PolicyRaw:   []byte(`{"issuer":{"name":"Self"}}`),
	}
}

func TestCreateAndGetCertificate(t *testing.T) {
	m := newTestMock()
	ctx := context.Background()

	created, err := m.CreateCertificate(ctx, "default", "cert", createParams())
	require.NoError(t, err)
	assert.NotEmpty(t, created.Version)
	assert.NotEmpty(t, created.CER)
	assert.Len(t, created.Thumbprint, 20) // SHA-1
	assert.True(t, created.Enabled)
	assert.Greater(t, created.Expires, created.NotBefore)

	// The generated bytes must be a parseable X.509 certificate with the CN.
	parsed, err := x509.ParseCertificate(created.CER)
	require.NoError(t, err)
	assert.Equal(t, "mycert.example.com", parsed.Subject.CommonName)
	assert.Equal(t, []string{"mycert.example.com"}, parsed.DNSNames)

	got, err := m.GetCertificate(ctx, "default", "cert", "")
	require.NoError(t, err)
	assert.Equal(t, created.Version, got.Version)
	assert.Equal(t, created.CER, got.CER)
	assert.JSONEq(t, `{"issuer":{"name":"Self"}}`, string(got.PolicyRaw))

	byVersion, err := m.GetCertificate(ctx, "default", "cert", created.Version)
	require.NoError(t, err)
	assert.Equal(t, created.Version, byVersion.Version)
}

func TestCertificateVersionsAndList(t *testing.T) {
	m := newTestMock()
	ctx := context.Background()

	first, err := m.CreateCertificate(ctx, "default", "cert", createParams())
	require.NoError(t, err)

	second, err := m.CreateCertificate(ctx, "default", "cert", createParams())
	require.NoError(t, err)
	assert.NotEqual(t, first.Version, second.Version)

	versions, err := m.ListCertificateVersions(ctx, "default", "cert")
	require.NoError(t, err)
	assert.Len(t, versions, 2)

	// Get with empty version returns the latest (current) version.
	current, err := m.GetCertificate(ctx, "default", "cert", "")
	require.NoError(t, err)
	assert.Equal(t, second.Version, current.Version)

	list, err := m.ListCertificates(ctx, "default")
	require.NoError(t, err)
	assert.Len(t, list, 1)
	assert.Equal(t, second.Version, list[0].Version)
}

func TestGetMissingCertificate(t *testing.T) {
	m := newTestMock()

	_, err := m.GetCertificate(context.Background(), "default", "nope", "")
	require.Error(t, err)
	assert.True(t, errors.IsNotFound(err))
}

func TestCertificateSoftDeleteRecoverPurge(t *testing.T) {
	m := newTestMock()
	ctx := context.Background()

	_, err := m.CreateCertificate(ctx, "default", "cert", createParams())
	require.NoError(t, err)

	deleted, err := m.DeleteCertificate(ctx, "default", "cert")
	require.NoError(t, err)
	assert.Greater(t, deleted.ScheduledPurgeDate, deleted.DeletedDate)

	// Live get now fails; deleted get succeeds.
	_, err = m.GetCertificate(ctx, "default", "cert", "")
	require.Error(t, err)
	assert.True(t, errors.IsNotFound(err))

	gotDeleted, err := m.GetDeletedCertificate(ctx, "default", "cert")
	require.NoError(t, err)
	assert.Equal(t, "cert", gotDeleted.Name)

	deletedList, err := m.ListDeletedCertificates(ctx, "default")
	require.NoError(t, err)
	assert.Len(t, deletedList, 1)

	recovered, err := m.RecoverDeletedCertificate(ctx, "default", "cert")
	require.NoError(t, err)
	assert.NotEmpty(t, recovered.CER)

	// Recovered certificate is live again; purge then removes it entirely.
	_, err = m.GetCertificate(ctx, "default", "cert", "")
	require.NoError(t, err)

	_, err = m.DeleteCertificate(ctx, "default", "cert")
	require.NoError(t, err)

	require.NoError(t, m.PurgeDeletedCertificate(ctx, "default", "cert"))

	_, err = m.GetDeletedCertificate(ctx, "default", "cert")
	require.Error(t, err)
	assert.True(t, errors.IsNotFound(err))
}

func TestCertificatesIsolatedByVault(t *testing.T) {
	m := newTestMock()
	ctx := context.Background()

	_, err := m.CreateCertificate(ctx, "vault-a", "shared", createParams())
	require.NoError(t, err)

	_, err = m.GetCertificate(ctx, "vault-b", "shared", "")
	require.Error(t, err)
	assert.True(t, errors.IsNotFound(err))

	listB, err := m.ListCertificates(ctx, "vault-b")
	require.NoError(t, err)
	assert.Empty(t, listB)
}

func TestCreateCertificateEmptyNameRejected(t *testing.T) {
	m := newTestMock()

	_, err := m.CreateCertificate(context.Background(), "default", "", createParams())
	require.Error(t, err)
	assert.True(t, errors.IsInvalidArgument(err))
}
