// Package driver defines the portable interface for the Google Cloud Dataproc
// cluster control plane (dataproc.googleapis.com/v1). It is control-plane only —
// clusters plus the long-running operations their mutating RPCs return. Job
// execution, cluster start/stop, workflow templates, autoscaling policies, and
// any real Hadoop/Spark runtime are deliberately out of scope.
//
// Dataproc is a REGION-scoped service: a cluster lives under a project and a
// region (projects/{p}/regions/{r}/clusters/{c}), not under a location or a
// zone. The operations a mutation returns are region-scoped too:
//
//	projects/{p}/regions/{r}/clusters/{c}
//	projects/{p}/regions/{r}/operations/{op}
package driver

import (
	"context"
	"time"
)

// Cluster lifecycle states (real Dataproc ClusterStatus.State enum). CloudEmu
// completes every mutation synchronously, so a created cluster reports RUNNING
// immediately (real Dataproc passes briefly through CREATING); the CREATING
// constant is retained for the status history entry and tests.
const (
	StateRunning  = "RUNNING"
	StateCreating = "CREATING"
	StateUpdating = "UPDATING"
	StateDeleting = "DELETING"
)

// DefaultImageVersion is the Dataproc image version a create request that omits
// softwareConfig.imageVersion resolves to. It is a stable, valid track so a
// Terraform read of a cluster created without an explicit version does not drift.
const DefaultImageVersion = "2.2-debian12"

// Cluster is a Dataproc cluster.
type Cluster struct {
	ProjectID     string
	Region        string
	ClusterName   string
	ClusterUUID   string // generated by the service at create; stable thereafter
	Config        ClusterConfig
	Labels        map[string]string
	Status        ClusterStatus
	StatusHistory []ClusterStatus
}

// ClusterConfig is the Compute Engine cluster config.
type ClusterConfig struct {
	ConfigBucket          string
	TempBucket            string
	GceClusterConfig      *GceClusterConfig
	MasterConfig          *InstanceGroupConfig
	WorkerConfig          *InstanceGroupConfig
	SecondaryWorkerConfig *InstanceGroupConfig
	SoftwareConfig        *SoftwareConfig
	InitializationActions []NodeInitializationAction
}

// GceClusterConfig holds the shared Compute Engine settings for every instance
// in a cluster.
type GceClusterConfig struct {
	ZoneURI        string
	NetworkURI     string
	SubnetworkURI  string
	ServiceAccount string
	InternalIPOnly bool
	Metadata       map[string]string
	Tags           []string
}

// InstanceGroupConfig is the config for one instance group (master, primary
// worker, or secondary worker).
type InstanceGroupConfig struct {
	NumInstances   int64
	MachineTypeURI string
	ImageURI       string
	MinCPUPlatform string
	IsPreemptible  bool
	Preemptibility string
	InstanceNames  []string
	DiskConfig     *DiskConfig
}

// DiskConfig is the disk config for an instance group.
type DiskConfig struct {
	BootDiskType   string
	BootDiskSizeGb int64
	NumLocalSsds   int64
}

// SoftwareConfig holds the cluster software settings.
type SoftwareConfig struct {
	ImageVersion       string
	Properties         map[string]string
	OptionalComponents []string
}

// NodeInitializationAction is an executable to run on each node after config.
type NodeInitializationAction struct {
	ExecutableFile   string
	ExecutionTimeout string
}

// ClusterStatus is a point-in-time cluster status.
type ClusterStatus struct {
	State          string
	Detail         string
	StateStartTime time.Time
	Substate       string
}

// CreateClusterConfig is the input to CreateCluster.
type CreateClusterConfig struct {
	ProjectID   string
	Region      string
	ClusterName string
	Config      ClusterConfig
	Labels      map[string]string
}

// UpdateClusterConfig is the input to UpdateCluster. FieldMask holds the
// normalized (lowercased) updateMask paths from the request; only the fields it
// names are written, matching real Dataproc, which requires an explicit mask.
type UpdateClusterConfig struct {
	FieldMask                   []string
	WorkerNumInstances          int64
	SecondaryWorkerNumInstances int64
	Labels                      map[string]string
}

// Operation is a completed long-running operation. Every CloudEmu mutation
// finishes synchronously, so Done is always true; the poller replays it so an
// SDK or Terraform LRO wait terminates on the first poll.
type Operation struct {
	Name       string // projects/{p}/regions/{r}/operations/{op}
	Done       bool
	TargetName string // the cluster the operation acted on
	Type       string // create | update | delete
}

// Dataproc is the cluster control-plane interface a provider implements.
type Dataproc interface {
	// CreateCluster provisions a new RUNNING cluster (returns a completed LRO).
	CreateCluster(ctx context.Context, cfg *CreateClusterConfig) (*Cluster, *Operation, error)
	// GetCluster returns a cluster by project/region/name.
	GetCluster(ctx context.Context, project, region, name string) (*Cluster, error)
	// ListClusters returns every cluster in a project+region.
	ListClusters(ctx context.Context, project, region string) ([]Cluster, error)
	// UpdateCluster applies a masked update to a cluster (returns a completed LRO).
	UpdateCluster(ctx context.Context, project, region, name string, cfg UpdateClusterConfig) (*Cluster, *Operation, error)
	// DeleteCluster removes a cluster (returns a completed LRO).
	DeleteCluster(ctx context.Context, project, region, name string) (*Operation, error)
	// GetOperation resolves a (done) long-running operation by name.
	GetOperation(ctx context.Context, name string) (*Operation, error)
}
