// Package driver defines the portable interface for the Google Cloud Composer
// environment control plane (composer.googleapis.com/v1). It is control-plane
// only — managed Apache Airflow environments plus the long-running operations
// their mutating RPCs return. No real Airflow runtime, DAG execution, GKE
// cluster, snapshot, or user-workload surface is modeled; those are out of
// scope.
//
// Composer is a LOCATION-scoped service: an environment lives under a project
// and a location (projects/{p}/locations/{loc}/environments/{env}). The
// operations a mutation returns are location-scoped too, sharing the operations
// space the shared GCP LRO poller owns:
//
//	projects/{p}/locations/{loc}/environments/{env}
//	projects/{p}/locations/{loc}/operations/{op}
package driver

import (
	"context"
	"encoding/json"
	"time"
)

// Environment lifecycle states (real Composer Environment.state enum). CloudEmu
// completes every mutation synchronously, so a created environment reports
// RUNNING immediately (real Composer passes through CREATING for ~25 minutes).
const (
	StateRunning  = "RUNNING"
	StateCreating = "CREATING"
	StateUpdating = "UPDATING"
	StateDeleting = "DELETING"
)

// DefaultImageVersion is the Composer image version a create request that omits
// softwareConfig.imageVersion resolves to. It is a stable, valid track so a
// Terraform read of an environment created without an explicit version does not
// drift.
const DefaultImageVersion = "composer-2.9.7-airflow-2.9.3"

// Environment is a Cloud Composer environment. Name components are stored
// separately so the full resource name and location scoping can be rebuilt
// without re-parsing.
type Environment struct {
	Project       string
	Location      string
	EnvironmentID string
	UUID          string // generated by the service at create; stable thereafter
	State         string
	CreateTime    time.Time
	UpdateTime    time.Time
	Labels        map[string]string
	Config        EnvironmentConfig
	StorageBucket string // output-only storageConfig.bucket (deterministic)
}

// EnvironmentConfig mirrors composer/v1 EnvironmentConfig. The fields Terraform
// and the SDK read back or mutate are modeled explicitly; every other config
// sub-block (privateEnvironmentConfig, databaseConfig, webServerConfig,
// encryptionConfig, maintenanceWindow, workloadsConfig,
// masterAuthorizedNetworksConfig, recoveryConfig, dataRetentionConfig,
// webServerNetworkAccessControl, …) is carried verbatim in Other so a read
// round-trips exactly, matching real Composer, without enumerating every nested
// type.
type EnvironmentConfig struct {
	NodeCount       int64
	EnvironmentSize string
	ResilienceMode  string
	SoftwareConfig  *SoftwareConfig
	NodeConfig      *NodeConfig

	// Computed OUTPUT-only fields, derived deterministically at create and stable
	// across reads so a Terraform refresh does not drift.
	GkeCluster      string
	DagGcsPrefix    string
	AirflowURI      string
	AirflowByoidURI string

	// Other carries every config sub-block CloudEmu does not model, keyed by its
	// JSON field name, so it round-trips verbatim.
	Other map[string]json.RawMessage
}

// SoftwareConfig holds the environment software settings.
type SoftwareConfig struct {
	ImageVersion           string
	AirflowConfigOverrides map[string]string
	PypiPackages           map[string]string
	EnvVariables           map[string]string
	PythonVersion          string
	SchedulerCount         int64
}

// NodeConfig holds the Kubernetes Engine cluster settings for the environment.
type NodeConfig struct {
	Location       string
	MachineType    string
	Network        string
	Subnetwork     string
	DiskSizeGb     int64
	ServiceAccount string
	Tags           []string
	OauthScopes    []string
}

// CreateEnvironmentConfig is the input to CreateEnvironment.
type CreateEnvironmentConfig struct {
	Project       string
	Location      string
	EnvironmentID string
	Labels        map[string]string
	Config        EnvironmentConfig
}

// Operation is a completed long-running operation. Every CloudEmu mutation
// finishes synchronously, so Done is always true; the shared poller replays it
// so an SDK or Terraform LRO wait terminates on the first poll.
type Operation struct {
	Name       string // projects/{p}/locations/{loc}/operations/{op}
	Done       bool
	TargetName string // the environment the operation acted on
	Type       string // create | update | delete
}

// Composer is the environment control-plane interface a provider implements.
type Composer interface {
	// CreateEnvironment provisions a new RUNNING environment (returns a completed
	// LRO). The computed output fields are derived deterministically.
	CreateEnvironment(ctx context.Context, cfg *CreateEnvironmentConfig) (*Environment, *Operation, error)
	// GetEnvironment returns an environment by project/location/id.
	GetEnvironment(ctx context.Context, project, location, id string) (*Environment, error)
	// ListEnvironments returns every environment in a project+location.
	ListEnvironments(ctx context.Context, project, location string) ([]Environment, error)
	// UpdateEnvironment applies a masked update from desired and returns a
	// completed LRO. Only the fields named in mask are written.
	UpdateEnvironment(
		ctx context.Context, project, location, id string, desired *EnvironmentConfig,
		labels map[string]string, mask []string,
	) (*Environment, *Operation, error)
	// DeleteEnvironment removes an environment (returns a completed LRO).
	DeleteEnvironment(ctx context.Context, project, location, id string) (*Operation, error)
	// GetOperation resolves a (done) long-running operation by name.
	GetOperation(ctx context.Context, name string) (*Operation, error)
}
