// Package driver defines the storage contract for Azure Front Door
// Standard/Premium (Microsoft.Cdn/profiles) and its two independently-addressable
// child resource types: afdEndpoints and originGroups.
//
// The modern Front Door is an Azure-only ARM "echo-class" surface. Unlike
// Application Gateway — whose children are inline-only pieces of a single
// whole-resource PUT — a Front Door endpoint and origin group each have their own
// PUT/GET/DELETE/List operation group under
// .../profiles/{profile}/afdEndpoints/{ep} and .../profiles/{profile}/originGroups/{og}.
// So the store is a parent profile store plus two child stores, each keyed by ARM
// addressing: profiles by (resourceGroup, name), children by
// (resourceGroup, profile, name). Deleting a profile cascades to every endpoint and
// origin group under it.
//
// The pieces the server-wide unmodeled-property echo cannot preserve are modeled
// explicitly: the profile's sku, location, kind and identity are top-level (outside
// the "properties" object the echo reaches), and the computed frontDoorId and
// endpoint hostName are derived deterministically by the wire handler so they stay
// stable across GETs. Everything else — a profile's originResponseTimeoutSeconds and
// deferred properties, an endpoint's enabledState, an origin group's
// loadBalancingSettings/healthProbeSettings and so on — is kept verbatim as generic
// JSON so explicit values (including an explicit 0 or false) round-trip unchanged.
// AWS and GCP have no equivalent.
package driver

import "context"

// AzureFrontDoorProfile is the natively-stored Microsoft.Cdn/profiles resource.
// SKUName, Location, Identity and Tags are modeled explicitly because the
// server-wide unmodeled-property echo only reaches the top-level "properties"
// object and so cannot preserve them. OtherProps holds every property under
// "properties" (originResponseTimeoutSeconds, logScrubbing, extendedProperties,
// ...) verbatim, keeping deferred sub-surfaces round-trip-safe.
type AzureFrontDoorProfile struct {
	Name          string
	ResourceGroup string
	Location      string
	SKUName       string
	Identity      map[string]any
	Tags          map[string]string
	OtherProps    map[string]any
	ETag          string
}

// AzureFrontDoorEndpoint is the natively-stored afdEndpoints child. Location and
// Tags are top-level; Properties holds enabledState,
// autoGeneratedDomainNameLabelScope, enforceMtls and any deferred keys verbatim.
// The computed hostName is derived by the wire handler and not stored.
type AzureFrontDoorEndpoint struct {
	Name          string
	ResourceGroup string
	Profile       string
	Location      string
	Tags          map[string]string
	Properties    map[string]any
	ETag          string
}

// AzureFrontDoorOriginGroup is the natively-stored originGroups child. It has no
// location and no tags (the ARM schema exposes only name + properties). Properties
// holds loadBalancingSettings, healthProbeSettings, sessionAffinityState,
// trafficRestorationTimeToHealedOrNewEndpointsInMinutes and any deferred keys
// verbatim, so explicit nested zeros survive a round-trip.
type AzureFrontDoorOriginGroup struct {
	Name          string
	ResourceGroup string
	Profile       string
	Properties    map[string]any
	ETag          string
}

// AzureFrontDoorProfiles is the Azure-only Front Door store. CreateOrUpdate is a
// full replace for each of the three types: a property absent from the payload is
// dropped, matching ARM's PUT semantics. Children are addressed by
// (resourceGroup, profile, name); creating or getting a child under a missing
// profile returns NotFound. An empty resourceGroup on a profile list means
// subscription-wide. Deleting a profile cascades to its endpoints and origin
// groups.
type AzureFrontDoorProfiles interface {
	// CreateOrUpdateProfile stores p as a full replace and reports whether it did
	// not previously exist (created==true → HTTP 201, else 200). The returned value
	// is a defensive copy.
	CreateOrUpdateProfile(
		ctx context.Context, rg, name string, p AzureFrontDoorProfile,
	) (stored *AzureFrontDoorProfile, created bool, err error)
	// GetProfile returns the profile identified by (resourceGroup, name), or NotFound.
	GetProfile(ctx context.Context, rg, name string) (*AzureFrontDoorProfile, error)
	// DeleteProfile removes the profile and cascades to every endpoint and origin
	// group under it, returning NotFound if the profile does not exist.
	DeleteProfile(ctx context.Context, rg, name string) error
	// ListProfiles returns the profiles in rg, or all when rg is empty
	// (subscription-wide list), ordered by key.
	ListProfiles(ctx context.Context, rg string) ([]AzureFrontDoorProfile, error)

	// CreateOrUpdateEndpoint stores e under (rg, profile, name) as a full replace,
	// reporting whether it did not previously exist. Returns NotFound if the parent
	// profile does not exist.
	CreateOrUpdateEndpoint(
		ctx context.Context, rg, profile, name string, e AzureFrontDoorEndpoint,
	) (stored *AzureFrontDoorEndpoint, created bool, err error)
	// GetEndpoint returns the endpoint identified by (rg, profile, name), or NotFound.
	GetEndpoint(ctx context.Context, rg, profile, name string) (*AzureFrontDoorEndpoint, error)
	// DeleteEndpoint removes the endpoint, returning NotFound if it does not exist.
	DeleteEndpoint(ctx context.Context, rg, profile, name string) error
	// ListEndpoints returns the endpoints under (rg, profile), ordered by key.
	ListEndpoints(ctx context.Context, rg, profile string) ([]AzureFrontDoorEndpoint, error)

	// CreateOrUpdateOriginGroup stores g under (rg, profile, name) as a full
	// replace, reporting whether it did not previously exist. Returns NotFound if
	// the parent profile does not exist.
	CreateOrUpdateOriginGroup(
		ctx context.Context, rg, profile, name string, g AzureFrontDoorOriginGroup,
	) (stored *AzureFrontDoorOriginGroup, created bool, err error)
	// GetOriginGroup returns the origin group identified by (rg, profile, name), or
	// NotFound.
	GetOriginGroup(ctx context.Context, rg, profile, name string) (*AzureFrontDoorOriginGroup, error)
	// DeleteOriginGroup removes the origin group, returning NotFound if it does not
	// exist.
	DeleteOriginGroup(ctx context.Context, rg, profile, name string) error
	// ListOriginGroups returns the origin groups under (rg, profile), ordered by key.
	ListOriginGroups(ctx context.Context, rg, profile string) ([]AzureFrontDoorOriginGroup, error)
}
