// Code generated by gcpenumgen. DO NOT EDIT.

package dataplex

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// lakeEnums maps each enum field of google.cloud.dataplex.v1.Lake, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var lakeEnums = gcpenum.Fields{
	"metastoreStatus.state": {Type: "google.cloud.dataplex.v1.Lake.MetastoreStatus.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "NONE",
		2: "READY",
		3: "UPDATING",
		4: "ERROR",
	}},
	"state": {Type: "google.cloud.dataplex.v1.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "CREATING",
		3: "DELETING",
		4: "ACTION_REQUIRED",
	}},
}

// zoneEnums maps each enum field of google.cloud.dataplex.v1.Zone, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var zoneEnums = gcpenum.Fields{
	"resourceSpec.locationType": {Type: "google.cloud.dataplex.v1.Zone.ResourceSpec.LocationType", Names: map[int32]string{
		0: "LOCATION_TYPE_UNSPECIFIED",
		1: "SINGLE_REGION",
		2: "MULTI_REGION",
	}},
	"state": {Type: "google.cloud.dataplex.v1.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "CREATING",
		3: "DELETING",
		4: "ACTION_REQUIRED",
	}},
	"type": {Type: "google.cloud.dataplex.v1.Zone.Type", Names: map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "RAW",
		2: "CURATED",
	}},
}

// assetEnums maps each enum field of google.cloud.dataplex.v1.Asset, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var assetEnums = gcpenum.Fields{
	"discoveryStatus.state": {Type: "google.cloud.dataplex.v1.Asset.DiscoveryStatus.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "SCHEDULED",
		2: "IN_PROGRESS",
		3: "PAUSED",
		5: "DISABLED",
	}},
	"resourceSpec.readAccessMode": {Type: "google.cloud.dataplex.v1.Asset.ResourceSpec.AccessMode", Names: map[int32]string{
		0: "ACCESS_MODE_UNSPECIFIED",
		1: "DIRECT",
		2: "MANAGED",
	}},
	"resourceSpec.type": {Type: "google.cloud.dataplex.v1.Asset.ResourceSpec.Type", Names: map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "STORAGE_BUCKET",
		2: "BIGQUERY_DATASET",
	}},
	"resourceStatus.state": {Type: "google.cloud.dataplex.v1.Asset.ResourceStatus.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "READY",
		2: "ERROR",
	}},
	"securityStatus.state": {Type: "google.cloud.dataplex.v1.Asset.SecurityStatus.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "READY",
		2: "APPLYING",
		3: "ERROR",
	}},
	"state": {Type: "google.cloud.dataplex.v1.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "CREATING",
		3: "DELETING",
		4: "ACTION_REQUIRED",
	}},
}
