package managedgrafana_test

import (
	"context"
	"strings"
	"testing"

	"github.com/stackshy/cloudemu/v2/config"
	cerrors "github.com/stackshy/cloudemu/v2/errors"
	"github.com/stackshy/cloudemu/v2/providers/azure/managedgrafana"
)

func newMock() *managedgrafana.Mock {
	return managedgrafana.New(config.NewOptions())
}

func ptr(s string) *string { return &s }

func standardInput() *managedgrafana.Input {
	return &managedgrafana.Input{
		Tags:                map[string]string{"env": "dev"},
		Identity:            &managedgrafana.Identity{Type: "SystemAssigned"},
		Sku:                 &managedgrafana.Sku{Name: "Standard"},
		GrafanaMajorVersion: ptr("10"),
		DeterministicOutIP:  ptr("Enabled"),
	}
}

func createStd(t *testing.T, m *managedgrafana.Mock) managedgrafana.Grafana {
	t.Helper()

	s, isNew, err := m.CreateOrUpdate(context.Background(), "sub", "rg", "graf1", "West US", standardInput())
	if err != nil || !isNew {
		t.Fatalf("create: err=%v isNew=%v", err, isNew)
	}

	return s
}

func TestCreateComputesStableFields(t *testing.T) {
	m := newMock()
	created := createStd(t, m)

	if created.ProvisioningState != "Succeeded" {
		t.Errorf("provisioningState = %q, want Succeeded", created.ProvisioningState)
	}

	wantEndpoint := "https://graf1-"
	if !strings.HasPrefix(created.Endpoint, wantEndpoint) ||
		!strings.HasSuffix(created.Endpoint, ".westus.grafana.azure.com") {
		t.Errorf("endpoint = %q, want %s...westus.grafana.azure.com", created.Endpoint, wantEndpoint)
	}

	if created.GrafanaVersion != "10.4.11" {
		t.Errorf("grafanaVersion = %q, want 10.4.11", created.GrafanaVersion)
	}

	if created.Sku == nil || created.Sku.Name != "Standard" {
		t.Errorf("sku = %+v, want name Standard", created.Sku)
	}

	if created.DomainNameLabelScope != "TenantReuse" {
		t.Errorf("autoGeneratedDomainNameLabelScope = %q, want TenantReuse", created.DomainNameLabelScope)
	}

	// ARM defaults for the toggles the request omitted.
	if created.PublicNetworkAccess != "Enabled" || created.ZoneRedundancy != "Disabled" || created.APIKey != "Disabled" {
		t.Errorf("toggle defaults wrong: pna=%q zr=%q apikey=%q",
			created.PublicNetworkAccess, created.ZoneRedundancy, created.APIKey)
	}

	if len(created.OutboundIPs) != 2 {
		t.Fatalf("outboundIPs = %v, want 2 deterministic IPs", created.OutboundIPs)
	}

	if created.Identity == nil || created.Identity.PrincipalID == "" || created.Identity.TenantID == "" {
		t.Errorf("system identity ids not minted: %+v", created.Identity)
	}
}

func TestGetStableAcrossReadsAndUpdates(t *testing.T) {
	ctx := context.Background()
	m := newMock()
	created := createStd(t, m)

	got1, err := m.Get(ctx, "sub", "rg", "graf1")
	if err != nil {
		t.Fatalf("get: %v", err)
	}

	// A tag-only PATCH must not move any computed field.
	updated, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "graf1", "West US", &managedgrafana.Input{
		Tags: map[string]string{"env": "prod"},
	})
	if err != nil {
		t.Fatalf("update: %v", err)
	}

	for _, tc := range []struct {
		name    string
		a, b, c string
	}{
		{"endpoint", created.Endpoint, got1.Endpoint, updated.Endpoint},
		{"grafanaVersion", created.GrafanaVersion, got1.GrafanaVersion, updated.GrafanaVersion},
		{"principalId", created.Identity.PrincipalID, got1.Identity.PrincipalID, updated.Identity.PrincipalID},
		{"tenantId", created.Identity.TenantID, got1.Identity.TenantID, updated.Identity.TenantID},
	} {
		if tc.a != tc.b || tc.b != tc.c {
			t.Errorf("%s drifted: create=%q get=%q update=%q", tc.name, tc.a, tc.b, tc.c)
		}
	}

	if updated.OutboundIPs[0] != created.OutboundIPs[0] {
		t.Errorf("outboundIPs drifted: %v vs %v", created.OutboundIPs, updated.OutboundIPs)
	}

	// PATCH replaced tags and preserved identity (omitted).
	if updated.Tags["env"] != "prod" || len(updated.Tags) != 1 {
		t.Errorf("tags not replaced: %v", updated.Tags)
	}

	if updated.Identity == nil {
		t.Errorf("identity wiped by tag-only patch")
	}
}

func TestPatchMergesToggles(t *testing.T) {
	ctx := context.Background()
	m := newMock()
	createStd(t, m)

	// PATCH only apiKey → other toggles preserved.
	updated, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "graf1", "West US", &managedgrafana.Input{
		APIKey: ptr("Enabled"),
	})
	if err != nil {
		t.Fatalf("patch: %v", err)
	}

	if updated.APIKey != "Enabled" {
		t.Errorf("apiKey = %q, want Enabled", updated.APIKey)
	}

	if updated.PublicNetworkAccess != "Enabled" || updated.DeterministicOutboundIP != "Enabled" {
		t.Errorf("preserved toggles wrong: pna=%q det=%q", updated.PublicNetworkAccess, updated.DeterministicOutboundIP)
	}

	if updated.GrafanaMajorVersion != "10" {
		t.Errorf("major version drifted: %q", updated.GrafanaMajorVersion)
	}
}

func TestDeterministicOutboundIPToggle(t *testing.T) {
	ctx := context.Background()
	m := newMock()

	s, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "graf2", "eastus", &managedgrafana.Input{
		DeterministicOutIP: ptr("Disabled"),
	})
	if err != nil {
		t.Fatalf("create: %v", err)
	}

	if len(s.OutboundIPs) != 0 {
		t.Errorf("outboundIPs = %v, want empty when disabled", s.OutboundIPs)
	}

	// Enable it → deterministic IPs appear.
	s2, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "graf2", "eastus", &managedgrafana.Input{
		DeterministicOutIP: ptr("Enabled"),
	})
	if err != nil {
		t.Fatalf("enable: %v", err)
	}

	if len(s2.OutboundIPs) != 2 {
		t.Errorf("outboundIPs = %v, want 2 when enabled", s2.OutboundIPs)
	}
}

func TestVersionDerivation(t *testing.T) {
	ctx := context.Background()
	m := newMock()

	cases := map[string]string{"9": "9.4.5", "11": "11.3.0", "99": "99.0.0"}
	for major, want := range cases {
		s, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "gv"+major, "eastus", &managedgrafana.Input{
			GrafanaMajorVersion: ptr(major),
		})
		if err != nil {
			t.Fatalf("create %s: %v", major, err)
		}

		if s.GrafanaVersion != want {
			t.Errorf("major %s -> version %q, want %q", major, s.GrafanaVersion, want)
		}
	}
}

func TestExplicitNoneClearsIdentity(t *testing.T) {
	ctx := context.Background()
	m := newMock()
	createStd(t, m)

	updated, _, err := m.CreateOrUpdate(ctx, "sub", "rg", "graf1", "West US", &managedgrafana.Input{
		Identity: &managedgrafana.Identity{Type: "None"},
	})
	if err != nil {
		t.Fatalf("patch: %v", err)
	}

	if updated.Identity != nil {
		t.Errorf("identity = %+v, want nil after None", updated.Identity)
	}
}

func TestGetNotFound(t *testing.T) {
	_, err := newMock().Get(context.Background(), "sub", "rg", "missing")
	if !cerrors.IsNotFound(err) {
		t.Errorf("err = %v, want NotFound", err)
	}
}

func TestDeleteIdempotent(t *testing.T) {
	ctx := context.Background()
	m := newMock()
	createStd(t, m)

	existed, err := m.Delete(ctx, "sub", "rg", "graf1")
	if err != nil || !existed {
		t.Fatalf("first delete: err=%v existed=%v", err, existed)
	}

	existed, err = m.Delete(ctx, "sub", "rg", "graf1")
	if err != nil || existed {
		t.Fatalf("second delete: err=%v existed=%v, want existed=false", err, existed)
	}
}

func TestListAndPurge(t *testing.T) {
	ctx := context.Background()
	m := newMock()

	for _, n := range []string{"a", "b"} {
		if _, _, err := m.CreateOrUpdate(ctx, "sub", "rg", n, "eastus", &managedgrafana.Input{}); err != nil {
			t.Fatalf("create %s: %v", n, err)
		}
	}

	if _, _, err := m.CreateOrUpdate(ctx, "sub", "rg2", "c", "eastus", &managedgrafana.Input{}); err != nil {
		t.Fatalf("create c: %v", err)
	}

	byRG, _ := m.ListByResourceGroup(ctx, "sub", "rg")
	if len(byRG) != 2 {
		t.Errorf("ListByResourceGroup = %d, want 2", len(byRG))
	}

	bySub, _ := m.ListBySubscription(ctx, "sub")
	if len(bySub) != 3 {
		t.Errorf("ListBySubscription = %d, want 3", len(bySub))
	}

	if err := m.PurgeResourceGroup(ctx, "sub", "rg"); err != nil {
		t.Fatalf("purge: %v", err)
	}

	bySub, _ = m.ListBySubscription(ctx, "sub")
	if len(bySub) != 1 {
		t.Errorf("after purge ListBySubscription = %d, want 1", len(bySub))
	}
}

func TestSnapshotRestore(t *testing.T) {
	ctx := context.Background()
	m := newMock()
	created := createStd(t, m)

	data, err := m.Snapshot(ctx, false)
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}

	restored := newMock()
	if err := restored.Restore(ctx, data); err != nil {
		t.Fatalf("restore: %v", err)
	}

	got, err := restored.Get(ctx, "sub", "rg", "graf1")
	if err != nil {
		t.Fatalf("get after restore: %v", err)
	}

	if got.Endpoint != created.Endpoint || got.Identity.PrincipalID != created.Identity.PrincipalID {
		t.Errorf("restore lost stable fields: endpoint %q vs %q", got.Endpoint, created.Endpoint)
	}
}

func TestValidation(t *testing.T) {
	ctx := context.Background()
	m := newMock()

	if _, _, err := m.CreateOrUpdate(ctx, "", "rg", "n", "eastus", &managedgrafana.Input{}); !cerrors.IsInvalidArgument(err) {
		t.Errorf("empty sub err = %v, want InvalidArgument", err)
	}
}
