// Package managedgrafana provides an in-memory mock of Azure Managed Grafana
// (Microsoft.Dashboard/grafana) — the ARM control plane only. It manages the
// grafana workspace lifecycle (create/update/get/delete/list); the data plane
// (dashboards, data sources, the Grafana HTTP API served from the instance
// endpoint) is out of scope.
//
// The resource carries a set of computed, service-minted fields that MUST stay
// stable for the lifetime of the resource so infrastructure-as-code tools
// (Terraform's azurerm_dashboard_grafana) see no drift on re-plan:
//   - endpoint: "https://<name>-<hash>.<region>.grafana.azure.com", deterministic
//     from the name and region.
//   - grafanaVersion: the full semantic version derived from grafanaMajorVersion.
//   - provisioningState: "Succeeded" once provisioning completes.
//   - outboundIPs: deterministic outbound IPs, populated only when
//     deterministicOutboundIP is Enabled.
//   - identity.principalId / identity.tenantId for a system-assigned identity.
//
// Every computed field is derived deterministically from the resource identity,
// so the same resource always reports the same values — across gets, patches and
// a snapshot/restore.
package managedgrafana

import (
	"context"
	"fmt"
	"maps"
	"slices"
	"sort"
	"strings"
	"sync"

	"github.com/stackshy/cloudemu/v2/config"
	cerrors "github.com/stackshy/cloudemu/v2/errors"
	"github.com/stackshy/cloudemu/v2/internal/idgen"
	"github.com/stackshy/cloudemu/v2/internal/memstore"
)

const (
	// providerNamespace is the ARM provider namespace.
	providerNamespace = "Microsoft.Dashboard"
	// resourceType is the ARM resource type segment.
	resourceType = "grafana"
	// stateSucceeded is the terminal provisioning state a synchronous ARM PUT
	// reaches immediately.
	stateSucceeded = "Succeeded"
	// endpointSuffix is the fixed tail of every Grafana instance endpoint host;
	// real Azure emits "https://<name>-<hash>.<region>.grafana.azure.com".
	endpointSuffix = "grafana.azure.com"
	// enabled / disabled are the ARM enum values for the toggle properties
	// (publicNetworkAccess, zoneRedundancy, apiKey, deterministicOutboundIP).
	enabled  = "Enabled"
	disabled = "Disabled"
	// tenantReuse is the only supported autoGeneratedDomainNameLabelScope value.
	tenantReuse = "TenantReuse"
	// defaultSkuName is the sku a Grafana workspace defaults to.
	defaultSkuName = "Standard"
	// defaultMajorVersion is the Grafana major version assumed when a request
	// omits grafanaMajorVersion.
	defaultMajorVersion = "10"
	// endpointHashLen is the number of hash characters in the endpoint host label.
	endpointHashLen = 16
)

// UserAssignedValue is the pair of ids Azure mints for a user-assigned identity
// once it is attached to a resource.
type UserAssignedValue struct {
	PrincipalID string `json:"principalId"`
	ClientID    string `json:"clientId"`
}

// Identity is a managed identity attached to a grafana resource. Type is one of
// SystemAssigned, UserAssigned or "SystemAssigned,UserAssigned". PrincipalID and
// TenantID are populated only for a system-assigned identity.
type Identity struct {
	Type         string                       `json:"type"`
	PrincipalID  string                       `json:"principalId,omitempty"`
	TenantID     string                       `json:"tenantId,omitempty"`
	UserAssigned map[string]UserAssignedValue `json:"userAssignedIdentities,omitempty"`
}

// Sku is the pricing tier of a grafana resource. Name is required (e.g.
// "Standard"). Size is an optional capacity tier echoed back when supplied.
type Sku struct {
	Name string `json:"name"`
	Size string `json:"size,omitempty"`
}

// Grafana is a stored Microsoft.Dashboard/grafana resource. Subscription,
// ResourceGroup and Name preserve the caller's casing; the computed fields are
// minted at create and never regenerated on a read.
type Grafana struct {
	Subscription  string            `json:"subscription"`
	ResourceGroup string            `json:"resourceGroup"`
	Name          string            `json:"name"`
	Location      string            `json:"location"`
	Tags          map[string]string `json:"tags,omitempty"`
	Identity      *Identity         `json:"identity,omitempty"`
	Sku           *Sku              `json:"sku,omitempty"`

	// Writable properties (ARM enum strings / config).
	PublicNetworkAccess     string   `json:"publicNetworkAccess"`
	ZoneRedundancy          string   `json:"zoneRedundancy"`
	APIKey                  string   `json:"apiKey"`
	DeterministicOutboundIP string   `json:"deterministicOutboundIP"`
	DomainNameLabelScope    string   `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	GrafanaMajorVersion     string   `json:"grafanaMajorVersion"`
	MonitorWorkspaceIDs     []string `json:"azureMonitorWorkspaceIntegrations,omitempty"`

	// Computed, stable fields.
	ProvisioningState string   `json:"provisioningState"`
	GrafanaVersion    string   `json:"grafanaVersion"`
	Endpoint          string   `json:"endpoint"`
	OutboundIPs       []string `json:"outboundIPs,omitempty"`
}

// ARMID returns the fully-qualified ARM resource id.
func (s *Grafana) ARMID() string {
	return idgen.AzureID(s.Subscription, s.ResourceGroup, providerNamespace, resourceType, s.Name)
}

// Input carries the mutable fields of a create/update request. The pointer
// fields distinguish "not supplied" (nil, preserve existing) from an explicit
// value, so a PATCH overlays only what it names.
type Input struct {
	Tags                 map[string]string
	Identity             *Identity
	Sku                  *Sku
	PublicNetworkAccess  *string
	ZoneRedundancy       *string
	APIKey               *string
	DeterministicOutIP   *string
	DomainNameLabelScope *string
	GrafanaMajorVersion  *string
	MonitorWorkspaceIDs  *[]string
}

// Mock is the in-memory backend for grafana resources.
type Mock struct {
	mu    sync.RWMutex
	store *memstore.Store[*Grafana]

	// tenantID is the single AAD tenant this estate belongs to; every
	// system-assigned identity reports it. Deterministic, so it survives a
	// restart without being persisted.
	tenantID string
}

// New creates an empty grafana mock.
func New(_ *config.Options) *Mock {
	return &Mock{
		store:    memstore.New[*Grafana](),
		tenantID: idgen.SyntheticGUID("cloudemu/azure/tenant"),
	}
}

// key is the case-insensitive store key for a resource.
func key(sub, rg, name string) string {
	return strings.ToLower(idgen.AzureID(sub, rg, providerNamespace, resourceType, name))
}

// CreateOrUpdate creates a new grafana resource or updates an existing one. The
// computed fields (endpoint, grafanaVersion, outboundIPs, identity ids) are
// minted deterministically so they stay stable across updates. Location and the
// autoGeneratedDomainNameLabelScope are immutable and preserved on update. It
// returns the stored resource and whether it was newly created.
func (m *Mock) CreateOrUpdate(_ context.Context, sub, rg, name, location string, in *Input) (Grafana, bool, error) {
	if err := validate(sub, rg, name); err != nil {
		return Grafana{}, false, err
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	k := key(sub, rg, name)

	existing, existed := m.store.Get(k)
	created := !existed

	var s Grafana
	if existed {
		s = *existing
	} else {
		s = newGrafana(sub, rg, name, location)
	}

	applyInput(&s, in)

	// Identity is re-resolved only when the request supplies one; a PATCH that
	// omits identity preserves the stored value (an explicit "None" clears it).
	if in.Identity != nil {
		s.Identity = m.resolveIdentity(in.Identity, sub, rg, name)
	}

	mintComputed(&s)

	m.store.Set(k, &s)

	return clone(&s), created, nil
}

// newGrafana seeds a fresh resource with its immutable identity, location and
// the ARM default toggle values.
func newGrafana(sub, rg, name, location string) Grafana {
	return Grafana{
		Subscription:            sub,
		ResourceGroup:           rg,
		Name:                    name,
		Location:                location,
		PublicNetworkAccess:     enabled,
		ZoneRedundancy:          disabled,
		APIKey:                  disabled,
		DeterministicOutboundIP: disabled,
		DomainNameLabelScope:    tenantReuse,
		GrafanaMajorVersion:     defaultMajorVersion,
		Sku:                     &Sku{Name: defaultSkuName},
		ProvisioningState:       stateSucceeded,
	}
}

// Get returns the resource, or a NotFound error.
func (m *Mock) Get(_ context.Context, sub, rg, name string) (Grafana, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	s, ok := m.store.Get(key(sub, rg, name))
	if !ok {
		return Grafana{}, cerrors.Newf(cerrors.NotFound, "grafana %q not found", name)
	}

	return clone(s), nil
}

// Delete removes the resource, reporting whether it existed.
func (m *Mock) Delete(_ context.Context, sub, rg, name string) (bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	return m.store.Delete(key(sub, rg, name)), nil
}

// ListByResourceGroup returns every resource in the group, sorted by name.
func (m *Mock) ListByResourceGroup(_ context.Context, sub, rg string) ([]Grafana, error) {
	return m.filter(func(s *Grafana) bool {
		return strings.EqualFold(s.Subscription, sub) && strings.EqualFold(s.ResourceGroup, rg)
	}), nil
}

// ListBySubscription returns every resource in the subscription, sorted by name.
func (m *Mock) ListBySubscription(_ context.Context, sub string) ([]Grafana, error) {
	return m.filter(func(s *Grafana) bool {
		return strings.EqualFold(s.Subscription, sub)
	}), nil
}

// DiscoverGrafana returns every stored resource, for the inventory walk.
func (m *Mock) DiscoverGrafana(_ context.Context) ([]Grafana, error) {
	return m.filter(func(*Grafana) bool { return true }), nil
}

// PurgeResourceGroup deletes every grafana resource under sub/rg, so a
// resource-group delete cascades into its grafana resources.
func (m *Mock) PurgeResourceGroup(_ context.Context, sub, rg string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	for k, s := range m.store.All() {
		if strings.EqualFold(s.Subscription, sub) && strings.EqualFold(s.ResourceGroup, rg) {
			m.store.Delete(k)
		}
	}

	return nil
}

// filter returns the resources matching pred, sorted by name for a stable order.
func (m *Mock) filter(pred func(*Grafana) bool) []Grafana {
	m.mu.RLock()
	defer m.mu.RUnlock()

	var out []Grafana

	for _, s := range m.store.All() {
		if pred(s) {
			out = append(out, clone(s))
		}
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })

	return out
}

// applyInput overlays the mutable request fields onto s, leaving the computed
// fields and the immutable location/domainNameLabelScope untouched. A nil
// pointer field means "not supplied": the stored value is preserved.
func applyInput(s *Grafana, in *Input) {
	if in.Tags != nil {
		s.Tags = maps.Clone(in.Tags)
	}

	if in.Sku != nil {
		s.Sku = &Sku{Name: in.Sku.Name, Size: in.Sku.Size}
	}

	overlayEnum(&s.PublicNetworkAccess, in.PublicNetworkAccess)
	overlayEnum(&s.ZoneRedundancy, in.ZoneRedundancy)
	overlayEnum(&s.APIKey, in.APIKey)
	overlayEnum(&s.DeterministicOutboundIP, in.DeterministicOutIP)

	if in.GrafanaMajorVersion != nil && *in.GrafanaMajorVersion != "" {
		s.GrafanaMajorVersion = *in.GrafanaMajorVersion
	}

	if in.MonitorWorkspaceIDs != nil {
		s.MonitorWorkspaceIDs = slices.Clone(*in.MonitorWorkspaceIDs)
	}
}

// overlayEnum copies a supplied non-empty toggle value onto dst.
func overlayEnum(dst, in *string) {
	if in != nil && *in != "" {
		*dst = normalizeEnum(*in)
	}
}

// mintComputed fills the stable, service-minted fields. Every value is derived
// deterministically from the stored identity, so it never changes on a read.
func mintComputed(s *Grafana) {
	s.ProvisioningState = stateSucceeded
	s.GrafanaVersion = versionFromMajor(s.GrafanaMajorVersion)
	s.Endpoint = endpointFor(s.Name, s.Location)

	if strings.EqualFold(s.DeterministicOutboundIP, enabled) {
		s.OutboundIPs = outboundIPsFor(s.Name)
	} else {
		s.OutboundIPs = nil
	}
}

// endpointFor builds the deterministic Grafana instance endpoint, matching the
// real "https://<name>-<hash>.<region>.grafana.azure.com" shape.
func endpointFor(name, location string) string {
	hash := strings.ReplaceAll(idgen.SyntheticGUID("grafana-endpoint/"+strings.ToLower(name)), "-", "")
	if len(hash) > endpointHashLen {
		hash = hash[:endpointHashLen]
	}

	return fmt.Sprintf("https://%s-%s.%s.%s", strings.ToLower(name), hash, regionCode(location), endpointSuffix)
}

// regionCode normalizes an ARM location into the host label real Azure uses in
// the endpoint (lowercased, whitespace removed). The exact value only has to be
// stable — Terraform reads the endpoint back verbatim.
func regionCode(location string) string {
	if location == "" {
		return "global"
	}

	return strings.ToLower(strings.ReplaceAll(location, " ", ""))
}

// outboundIPsFor mints two stable outbound IPs from the resource name, populated
// only when deterministicOutboundIP is Enabled.
func outboundIPsFor(name string) []string {
	const secondOctetOffset = 2

	seed := idgen.SyntheticGUID("grafana-outbound/" + strings.ToLower(name))
	octets := strings.ReplaceAll(seed, "-", "")

	// Two variable octets are sourced from adjacent hash nibbles; the leading
	// "20." block and the trailing host octets are fixed.
	a := byteFromHex(octets, 0)
	b := byteFromHex(octets, secondOctetOffset)

	return []string{
		fmt.Sprintf("20.%d.%d.10", a, b),
		fmt.Sprintf("20.%d.%d.11", a, b),
	}
}

// byteFromHex reads two hex chars at offset from s into a 0-255 value, clamped
// so it is a valid octet. Missing chars fall back to 0.
func byteFromHex(s string, offset int) int {
	const hexBase = 16

	v := 0

	for i := 0; i < 2; i++ {
		idx := offset + i
		if idx >= len(s) {
			break
		}

		v = v*hexBase + hexDigit(s[idx])
	}

	return v
}

// hexDigit maps a hex character to its value, defaulting to 0.
func hexDigit(c byte) int {
	switch {
	case c >= '0' && c <= '9':
		return int(c - '0')
	case c >= 'a' && c <= 'f':
		return int(c-'a') + 10 //nolint:mnd // hex letter offset.
	default:
		return 0
	}
}

// versionFromMajor derives the stable full Grafana semantic version reported for
// a major version. Unknown majors fall back to "<major>.0.0"; a blank major uses
// the default.
func versionFromMajor(major string) string {
	if major == "" {
		major = defaultMajorVersion
	}

	known := map[string]string{
		"9":  "9.4.5",
		"10": "10.4.11",
		"11": "11.3.0",
		"12": "12.0.0",
		"13": "13.1.0",
	}

	if v, ok := known[major]; ok {
		return v
	}

	return major + ".0.0"
}

// normalizeEnum canonicalizes a toggle value to the ARM "Enabled"/"Disabled"
// casing, leaving any other value untouched.
func normalizeEnum(v string) string {
	switch {
	case strings.EqualFold(v, enabled):
		return enabled
	case strings.EqualFold(v, disabled):
		return disabled
	default:
		return v
	}
}

// resolveIdentity normalizes an incoming managed identity, synthesizing the
// deterministic ids Azure mints on assignment. A nil or "None" identity resolves
// to nil.
func (m *Mock) resolveIdentity(in *Identity, sub, rg, name string) *Identity {
	if in == nil || in.Type == "" || strings.EqualFold(in.Type, "None") {
		return nil
	}

	out := &Identity{Type: in.Type}

	if strings.Contains(strings.ToLower(in.Type), "systemassigned") {
		id := strings.ToLower(idgen.AzureID(sub, rg, providerNamespace, resourceType, name))
		out.PrincipalID = idgen.SyntheticGUID("principal/" + id)
		out.TenantID = m.tenantID
	}

	if len(in.UserAssigned) > 0 {
		out.UserAssigned = make(map[string]UserAssignedValue, len(in.UserAssigned))
		for id := range in.UserAssigned {
			out.UserAssigned[id] = UserAssignedValue{
				PrincipalID: idgen.SyntheticGUID("ua-principal/" + strings.ToLower(id)),
				ClientID:    idgen.SyntheticGUID("ua-client/" + strings.ToLower(id)),
			}
		}
	}

	return out
}

// validate rejects a create/update with missing required identity fields.
func validate(sub, rg, name string) error {
	switch {
	case sub == "":
		return cerrors.New(cerrors.InvalidArgument, "subscription is required")
	case rg == "":
		return cerrors.New(cerrors.InvalidArgument, "resource group is required")
	case name == "":
		return cerrors.New(cerrors.InvalidArgument, "grafana name is required")
	default:
		return nil
	}
}

// clone deep-copies a stored resource so callers never alias the backing store.
func clone(s *Grafana) Grafana {
	out := *s
	out.Tags = maps.Clone(s.Tags)
	out.MonitorWorkspaceIDs = slices.Clone(s.MonitorWorkspaceIDs)
	out.OutboundIPs = slices.Clone(s.OutboundIPs)

	if s.Sku != nil {
		sku := *s.Sku
		out.Sku = &sku
	}

	if s.Identity != nil {
		id := *s.Identity
		id.UserAssigned = maps.Clone(s.Identity.UserAssigned)
		out.Identity = &id
	}

	return out
}
