package firestore

import (
	"net/http"
	"strings"

	cerrors "github.com/stackshy/cloudemu/v2/errors"
	"github.com/stackshy/cloudemu/v2/server/wire/gcprest"
)

// Index enum canonical names.
const (
	queryScopeCollection      = "COLLECTION"
	queryScopeCollectionGroup = "COLLECTION_GROUP"

	apiScopeAny = "ANY_API"

	orderAscending  = "ASCENDING"
	orderDescending = "DESCENDING"

	arrayConfigContains = "CONTAINS"

	indexStateReady = "READY"
)

//nolint:gochecknoglobals // static enum lookup tables (int→name) for index request normalization.
var (
	queryScopeByInt = map[int32]string{
		1: queryScopeCollection, 2: queryScopeCollectionGroup, 3: "COLLECTION_RECURSIVE",
	}

	apiScopeByInt = map[int32]string{0: apiScopeAny, 1: "DATASTORE_MODE_API", 2: "MONGODB_COMPATIBLE_API"}

	orderByInt = map[int32]string{1: orderAscending, 2: orderDescending}

	arrayConfigByInt = map[int32]string{1: arrayConfigContains}
)

// indexFieldRec is one field of a composite index.
type indexFieldRec struct {
	fieldPath   string
	order       string // set when the field is ordered
	arrayConfig string // set when the field is an array-contains
}

// indexRecord is the stored metadata for one composite index.
type indexRecord struct {
	project    string
	database   string
	collGroup  string
	indexID    string
	queryScope string
	apiScope   string
	fields     []indexFieldRec
}

// parseIndexPath parses .../collectionGroups/{cg}/indexes[/{i}] into p. It
// returns false for the collectionGroups/.../fields surface (not implemented)
// and any malformed shape.
func parseIndexPath(parts []string, p *adminPath) bool {
	const (
		collLen  = 7 // projects/p/databases/db/collectionGroups/cg/indexes
		indexLen = 8 // projects/p/databases/db/collectionGroups/cg/indexes/{i}
		idxKind  = 6
	)

	if len(parts) != collLen && len(parts) != indexLen {
		return false
	}

	if parts[idxKind] != segIndexes {
		return false
	}

	p.collGroup = parts[5]

	if len(parts) == collLen {
		p.isIndexColl = true
		return true
	}

	p.index = parts[7]

	return true
}

// serveIndexCollection handles the indexes collection: POST (create) and GET
// (list).
func (h *AdminHandler) serveIndexCollection(w http.ResponseWriter, r *http.Request, p *adminPath) {
	switch r.Method {
	case http.MethodPost:
		h.createIndex(w, r, p)
	case http.MethodGet:
		h.listIndexes(w, p)
	default:
		gcprest.WriteError(w, http.StatusMethodNotAllowed, "methodNotAllowed", "method not allowed")
	}
}

// serveIndexResource handles a single index: GET and DELETE.
func (h *AdminHandler) serveIndexResource(w http.ResponseWriter, r *http.Request, p *adminPath) {
	switch r.Method {
	case http.MethodGet:
		h.getIndex(w, p)
	case http.MethodDelete:
		h.deleteIndex(w, p)
	default:
		gcprest.WriteError(w, http.StatusMethodNotAllowed, "methodNotAllowed", "method not allowed")
	}
}

// indexKey is the store key for an index resource name.
func indexKey(project, database, collGroup, indexID string) string {
	return "projects/" + project + "/databases/" + database +
		"/collectionGroups/" + collGroup + "/indexes/" + indexID
}

// createIndex implements FirestoreAdmin.CreateIndex (an LRO). The database must
// exist. The generated index id is returned via the operation's Index response.
func (h *AdminHandler) createIndex(w http.ResponseWriter, r *http.Request, p *adminPath) {
	if !h.databases.Has(dbKey(p.project, p.database)) {
		gcprest.WriteCErr(w, cerrors.Newf(cerrors.NotFound, "database %q not found", p.database))
		return
	}

	body, ok := decodeAdminBody(w, r)
	if !ok {
		return
	}

	rec, err := buildIndexRecord(p, body)
	if err != nil {
		gcprest.WriteCErr(w, err)
		return
	}

	name := indexKey(rec.project, rec.database, rec.collGroup, rec.indexID)
	h.indexes.Set(name, rec)

	// IndexOperationMetadata carries the server-assigned index name; the
	// Terraform firestore_index resource reads it out of metadata.index because
	// the index id is generated by the server, not the client.
	metadata := map[string]any{
		"@type": "type.googleapis.com/google.firestore.admin.v1.IndexOperationMetadata",
		"index": name,
		"state": indexStateReady,
	}
	h.writeDoneOperationMeta(w, p.project, p.database, indexAnyResponse(&rec), metadata)
}

// getIndex implements FirestoreAdmin.GetIndex.
func (h *AdminHandler) getIndex(w http.ResponseWriter, p *adminPath) {
	rec, ok := h.indexes.Get(indexKey(p.project, p.database, p.collGroup, p.index))
	if !ok {
		gcprest.WriteCErr(w, cerrors.Newf(cerrors.NotFound, "index %q not found", p.index))
		return
	}

	gcprest.WriteJSON(w, http.StatusOK, renderIndex(&rec))
}

// listIndexes implements FirestoreAdmin.ListIndexes for a collection group.
func (h *AdminHandler) listIndexes(w http.ResponseWriter, p *adminPath) {
	prefix := "projects/" + p.project + "/databases/" + p.database +
		"/collectionGroups/" + p.collGroup + "/indexes/"

	var out []map[string]any

	for _, key := range h.indexes.Keys() {
		if !strings.HasPrefix(key, prefix) {
			continue
		}

		if rec, ok := h.indexes.Get(key); ok {
			out = append(out, renderIndex(&rec))
		}
	}

	gcprest.WriteJSON(w, http.StatusOK, map[string]any{"indexes": out})
}

// deleteIndex implements FirestoreAdmin.DeleteIndex. Real DeleteIndex returns an
// empty body (google.protobuf.Empty), not an operation.
func (h *AdminHandler) deleteIndex(w http.ResponseWriter, p *adminPath) {
	key := indexKey(p.project, p.database, p.collGroup, p.index)
	if !h.indexes.Delete(key) {
		gcprest.WriteCErr(w, cerrors.Newf(cerrors.NotFound, "index %q not found", p.index))
		return
	}

	gcprest.WriteJSON(w, http.StatusOK, map[string]any{})
}

// buildIndexRecord constructs an index record from a create body.
func buildIndexRecord(p *adminPath, body map[string]any) (indexRecord, error) {
	rec := indexRecord{
		project:    p.project,
		database:   p.database,
		collGroup:  p.collGroup,
		indexID:    "index-" + randHex(),
		queryScope: queryScopeCollection,
		apiScope:   apiScopeAny,
	}

	if raw, present := body["queryScope"]; present {
		v, err := enumValue(raw, queryScopeByInt, "queryScope")
		if err != nil {
			return indexRecord{}, err
		}

		rec.queryScope = v
	}

	if raw, present := body["apiScope"]; present {
		v, err := enumValue(raw, apiScopeByInt, "apiScope")
		if err != nil {
			return indexRecord{}, err
		}

		rec.apiScope = v
	}

	fields, err := parseIndexFields(body["fields"])
	if err != nil {
		return indexRecord{}, err
	}

	rec.fields = fields

	return rec, nil
}

// parseIndexFields normalizes the fields array of an index create body.
func parseIndexFields(raw any) ([]indexFieldRec, error) {
	list, ok := raw.([]any)
	if !ok {
		return nil, nil
	}

	out := make([]indexFieldRec, 0, len(list))

	for _, item := range list {
		m, ok := item.(map[string]any)
		if !ok {
			return nil, cerrors.New(cerrors.InvalidArgument, "invalid index field")
		}

		fr := indexFieldRec{fieldPath: stringField(m, "fieldPath")}

		if err := assignFieldMode(&fr, m); err != nil {
			return nil, err
		}

		out = append(out, fr)
	}

	return out, nil
}

// assignFieldMode sets the order or arrayConfig of one index field.
func assignFieldMode(fr *indexFieldRec, m map[string]any) error {
	if raw, present := m["order"]; present {
		v, err := enumValue(raw, orderByInt, "order")
		if err != nil {
			return err
		}

		fr.order = v
	}

	if raw, present := m["arrayConfig"]; present {
		v, err := enumValue(raw, arrayConfigByInt, "arrayConfig")
		if err != nil {
			return err
		}

		fr.arrayConfig = v
	}

	return nil
}

// renderIndex builds the JSON map for an Index resource.
func renderIndex(rec *indexRecord) map[string]any {
	fields := make([]map[string]any, 0, len(rec.fields))

	for _, f := range rec.fields {
		fm := map[string]any{"fieldPath": f.fieldPath}
		if f.order != "" {
			fm["order"] = f.order
		}

		if f.arrayConfig != "" {
			fm["arrayConfig"] = f.arrayConfig
		}

		fields = append(fields, fm)
	}

	return map[string]any{
		"name":       indexKey(rec.project, rec.database, rec.collGroup, rec.indexID),
		"queryScope": rec.queryScope,
		"apiScope":   rec.apiScope,
		"fields":     fields,
		"state":      indexStateReady,
	}
}

// indexAnyResponse wraps a rendered index as an Operation response Any.
func indexAnyResponse(rec *indexRecord) map[string]any {
	out := renderIndex(rec)
	out["@type"] = "type.googleapis.com/google.firestore.admin.v1.Index"

	return out
}
