package glue

import (
	"context"
	"net/http"
)

// synthHandler decodes the request as a generic JSON object, invokes the driver
// method, and writes the returned object. Used for every synthesized operation
// (see the driver's synth.go): the wire contract is preserved without modeling
// a typed request/response shape for surfaces that have no real data plane.
func (h *Handler) synthHandler(
	fn func(context.Context, map[string]any) (map[string]any, error),
) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		dispatch(h, w, r, func(_ *Handler, ctx context.Context, req *map[string]any) (any, error) {
			return fn(ctx, *req)
		})
	}
}

// registerSynthesizedRoutes wires every synthesized operation to the matching
// driver method via the generic synthHandler.
//
//nolint:funlen // a flat route table; one line per operation is the clearest form
func (h *Handler) registerSynthesizedRoutes() {
	h.routes["AssociateGlossaryTerms"] = h.synthHandler(h.glue.AssociateGlossaryTerms)
	h.routes["BatchGetCustomEntityTypes"] = h.synthHandler(h.glue.BatchGetCustomEntityTypes)
	h.routes["BatchGetDataQualityResult"] = h.synthHandler(h.glue.BatchGetDataQualityResult)
	h.routes["BatchGetDataQualityRulesetEvaluationRun"] = h.synthHandler(h.glue.BatchGetDataQualityRulesetEvaluationRun)
	h.routes["BatchGetIterableForms"] = h.synthHandler(h.glue.BatchGetIterableForms)
	h.routes["BatchGetTableOptimizer"] = h.synthHandler(h.glue.BatchGetTableOptimizer)
	h.routes["BatchPutDataQualityStatisticAnnotation"] = h.synthHandler(h.glue.BatchPutDataQualityStatisticAnnotation)
	h.routes["CancelDataQualityRuleRecommendationRun"] = h.synthHandler(h.glue.CancelDataQualityRuleRecommendationRun)
	h.routes["CancelDataQualityRulesetEvaluationRun"] = h.synthHandler(h.glue.CancelDataQualityRulesetEvaluationRun)
	h.routes["CancelMLTaskRun"] = h.synthHandler(h.glue.CancelMLTaskRun)
	h.routes["CancelStatement"] = h.synthHandler(h.glue.CancelStatement)
	h.routes["CreateColumnStatisticsTaskSettings"] = h.synthHandler(h.glue.CreateColumnStatisticsTaskSettings)
	h.routes["CreateCustomEntityType"] = h.synthHandler(h.glue.CreateCustomEntityType)
	h.routes["CreateDataQualityRuleset"] = h.synthHandler(h.glue.CreateDataQualityRuleset)
	h.routes["CreateGlossary"] = h.synthHandler(h.glue.CreateGlossary)
	h.routes["CreateGlossaryTerm"] = h.synthHandler(h.glue.CreateGlossaryTerm)
	h.routes["CreateGlueIdentityCenterConfiguration"] = h.synthHandler(h.glue.CreateGlueIdentityCenterConfiguration)
	h.routes["CreateIntegration"] = h.synthHandler(h.glue.CreateIntegration)
	h.routes["CreateIntegrationResourceProperty"] = h.synthHandler(h.glue.CreateIntegrationResourceProperty)
	h.routes["CreateIntegrationTableProperties"] = h.synthHandler(h.glue.CreateIntegrationTableProperties)
	h.routes["CreateMLTransform"] = h.synthHandler(h.glue.CreateMLTransform)
	h.routes["CreatePartitionIndex"] = h.synthHandler(h.glue.CreatePartitionIndex)
	h.routes["CreateScript"] = h.synthHandler(h.glue.CreateScript)
	h.routes["CreateSession"] = h.synthHandler(h.glue.CreateSession)
	h.routes["CreateTableOptimizer"] = h.synthHandler(h.glue.CreateTableOptimizer)
	h.routes["CreateUsageProfile"] = h.synthHandler(h.glue.CreateUsageProfile)
	h.routes["DeleteAsset"] = h.synthHandler(h.glue.DeleteAsset)
	h.routes["DeleteAssetType"] = h.synthHandler(h.glue.DeleteAssetType)
	h.routes["DeleteAttachment"] = h.synthHandler(h.glue.DeleteAttachment)
	h.routes["DeleteColumnStatisticsForPartition"] = h.synthHandler(h.glue.DeleteColumnStatisticsForPartition)
	h.routes["DeleteColumnStatisticsForTable"] = h.synthHandler(h.glue.DeleteColumnStatisticsForTable)
	h.routes["DeleteColumnStatisticsTaskSettings"] = h.synthHandler(h.glue.DeleteColumnStatisticsTaskSettings)
	h.routes["DeleteConnectionType"] = h.synthHandler(h.glue.DeleteConnectionType)
	h.routes["DeleteCustomEntityType"] = h.synthHandler(h.glue.DeleteCustomEntityType)
	h.routes["DeleteDataQualityRuleset"] = h.synthHandler(h.glue.DeleteDataQualityRuleset)
	h.routes["DeleteFormType"] = h.synthHandler(h.glue.DeleteFormType)
	h.routes["DeleteGlossary"] = h.synthHandler(h.glue.DeleteGlossary)
	h.routes["DeleteGlossaryTerm"] = h.synthHandler(h.glue.DeleteGlossaryTerm)
	h.routes["DeleteGlueIdentityCenterConfiguration"] = h.synthHandler(h.glue.DeleteGlueIdentityCenterConfiguration)
	h.routes["DeleteIntegration"] = h.synthHandler(h.glue.DeleteIntegration)
	h.routes["DeleteIntegrationResourceProperty"] = h.synthHandler(h.glue.DeleteIntegrationResourceProperty)
	h.routes["DeleteIntegrationTableProperties"] = h.synthHandler(h.glue.DeleteIntegrationTableProperties)
	h.routes["DeleteMLTransform"] = h.synthHandler(h.glue.DeleteMLTransform)
	h.routes["DeletePartitionIndex"] = h.synthHandler(h.glue.DeletePartitionIndex)
	h.routes["DeleteSession"] = h.synthHandler(h.glue.DeleteSession)
	h.routes["DeleteTableOptimizer"] = h.synthHandler(h.glue.DeleteTableOptimizer)
	h.routes["DeleteUsageProfile"] = h.synthHandler(h.glue.DeleteUsageProfile)
	h.routes["DescribeConnectionType"] = h.synthHandler(h.glue.DescribeConnectionType)
	h.routes["DescribeEntity"] = h.synthHandler(h.glue.DescribeEntity)
	h.routes["DescribeInboundIntegrations"] = h.synthHandler(h.glue.DescribeInboundIntegrations)
	h.routes["DescribeIntegrations"] = h.synthHandler(h.glue.DescribeIntegrations)
	h.routes["DisassociateGlossaryTerms"] = h.synthHandler(h.glue.DisassociateGlossaryTerms)
	h.routes["GetAsset"] = h.synthHandler(h.glue.GetAsset)
	h.routes["GetAssetType"] = h.synthHandler(h.glue.GetAssetType)
	h.routes["GetCatalogImportStatus"] = h.synthHandler(h.glue.GetCatalogImportStatus)
	h.routes["GetColumnStatisticsForPartition"] = h.synthHandler(h.glue.GetColumnStatisticsForPartition)
	h.routes["GetColumnStatisticsForTable"] = h.synthHandler(h.glue.GetColumnStatisticsForTable)
	h.routes["GetColumnStatisticsTaskRun"] = h.synthHandler(h.glue.GetColumnStatisticsTaskRun)
	h.routes["GetColumnStatisticsTaskRuns"] = h.synthHandler(h.glue.GetColumnStatisticsTaskRuns)
	h.routes["GetColumnStatisticsTaskSettings"] = h.synthHandler(h.glue.GetColumnStatisticsTaskSettings)
	h.routes["GetCrawlerMetrics"] = h.synthHandler(h.glue.GetCrawlerMetrics)
	h.routes["GetCustomEntityType"] = h.synthHandler(h.glue.GetCustomEntityType)
	h.routes["GetDashboardUrl"] = h.synthHandler(h.glue.GetDashboardUrl)
	h.routes["GetDataCatalogExportConfiguration"] = h.synthHandler(h.glue.GetDataCatalogExportConfiguration)
	h.routes["GetDataflowGraph"] = h.synthHandler(h.glue.GetDataflowGraph)
	h.routes["GetDataQualityModel"] = h.synthHandler(h.glue.GetDataQualityModel)
	h.routes["GetDataQualityModelResult"] = h.synthHandler(h.glue.GetDataQualityModelResult)
	h.routes["GetDataQualityResult"] = h.synthHandler(h.glue.GetDataQualityResult)
	h.routes["GetDataQualityRuleRecommendationRun"] = h.synthHandler(h.glue.GetDataQualityRuleRecommendationRun)
	h.routes["GetDataQualityRuleset"] = h.synthHandler(h.glue.GetDataQualityRuleset)
	h.routes["GetDataQualityRulesetEvaluationRun"] = h.synthHandler(h.glue.GetDataQualityRulesetEvaluationRun)
	h.routes["GetEntityRecords"] = h.synthHandler(h.glue.GetEntityRecords)
	h.routes["GetFormType"] = h.synthHandler(h.glue.GetFormType)
	h.routes["GetGlossary"] = h.synthHandler(h.glue.GetGlossary)
	h.routes["GetGlossaryTerm"] = h.synthHandler(h.glue.GetGlossaryTerm)
	h.routes["GetGlueIdentityCenterConfiguration"] = h.synthHandler(h.glue.GetGlueIdentityCenterConfiguration)
	h.routes["GetIntegrationResourceProperty"] = h.synthHandler(h.glue.GetIntegrationResourceProperty)
	h.routes["GetIntegrationTableProperties"] = h.synthHandler(h.glue.GetIntegrationTableProperties)
	h.routes["GetJobBookmark"] = h.synthHandler(h.glue.GetJobBookmark)
	h.routes["GetMapping"] = h.synthHandler(h.glue.GetMapping)
	h.routes["GetMaterializedViewRefreshTaskRun"] = h.synthHandler(h.glue.GetMaterializedViewRefreshTaskRun)
	h.routes["GetMLTaskRun"] = h.synthHandler(h.glue.GetMLTaskRun)
	h.routes["GetMLTaskRuns"] = h.synthHandler(h.glue.GetMLTaskRuns)
	h.routes["GetMLTransform"] = h.synthHandler(h.glue.GetMLTransform)
	h.routes["GetMLTransforms"] = h.synthHandler(h.glue.GetMLTransforms)
	h.routes["GetPartitionIndexes"] = h.synthHandler(h.glue.GetPartitionIndexes)
	h.routes["GetPlan"] = h.synthHandler(h.glue.GetPlan)
	h.routes["GetResourcePolicies"] = h.synthHandler(h.glue.GetResourcePolicies)
	h.routes["GetSession"] = h.synthHandler(h.glue.GetSession)
	h.routes["GetSessionEndpoint"] = h.synthHandler(h.glue.GetSessionEndpoint)
	h.routes["GetStatement"] = h.synthHandler(h.glue.GetStatement)
	h.routes["GetTableOptimizer"] = h.synthHandler(h.glue.GetTableOptimizer)
	h.routes["GetUnfilteredPartitionMetadata"] = h.synthHandler(h.glue.GetUnfilteredPartitionMetadata)
	h.routes["GetUnfilteredPartitionsMetadata"] = h.synthHandler(h.glue.GetUnfilteredPartitionsMetadata)
	h.routes["GetUnfilteredTableMetadata"] = h.synthHandler(h.glue.GetUnfilteredTableMetadata)
	h.routes["GetUsageProfile"] = h.synthHandler(h.glue.GetUsageProfile)
	h.routes["ImportCatalogToGlue"] = h.synthHandler(h.glue.ImportCatalogToGlue)
	h.routes["ListAssetTypes"] = h.synthHandler(h.glue.ListAssetTypes)
	h.routes["ListColumnStatisticsTaskRuns"] = h.synthHandler(h.glue.ListColumnStatisticsTaskRuns)
	h.routes["ListConnectionTypes"] = h.synthHandler(h.glue.ListConnectionTypes)
	h.routes["ListCrawls"] = h.synthHandler(h.glue.ListCrawls)
	h.routes["ListCustomEntityTypes"] = h.synthHandler(h.glue.ListCustomEntityTypes)
	h.routes["ListDataQualityResults"] = h.synthHandler(h.glue.ListDataQualityResults)
	h.routes["ListDataQualityRuleRecommendationRuns"] = h.synthHandler(h.glue.ListDataQualityRuleRecommendationRuns)
	h.routes["ListDataQualityRulesetEvaluationRuns"] = h.synthHandler(h.glue.ListDataQualityRulesetEvaluationRuns)
	h.routes["ListDataQualityRulesets"] = h.synthHandler(h.glue.ListDataQualityRulesets)
	h.routes["ListDataQualityStatisticAnnotations"] = h.synthHandler(h.glue.ListDataQualityStatisticAnnotations)
	h.routes["ListDataQualityStatistics"] = h.synthHandler(h.glue.ListDataQualityStatistics)
	h.routes["ListEntities"] = h.synthHandler(h.glue.ListEntities)
	h.routes["ListFormTypes"] = h.synthHandler(h.glue.ListFormTypes)
	h.routes["ListGlossaries"] = h.synthHandler(h.glue.ListGlossaries)
	h.routes["ListGlossaryTerms"] = h.synthHandler(h.glue.ListGlossaryTerms)
	h.routes["ListIntegrationResourceProperties"] = h.synthHandler(h.glue.ListIntegrationResourceProperties)
	h.routes["ListIterableForms"] = h.synthHandler(h.glue.ListIterableForms)
	h.routes["ListMaterializedViewRefreshTaskRuns"] = h.synthHandler(h.glue.ListMaterializedViewRefreshTaskRuns)
	h.routes["ListMLTransforms"] = h.synthHandler(h.glue.ListMLTransforms)
	h.routes["ListSessions"] = h.synthHandler(h.glue.ListSessions)
	h.routes["ListStatements"] = h.synthHandler(h.glue.ListStatements)
	h.routes["ListTableOptimizerRuns"] = h.synthHandler(h.glue.ListTableOptimizerRuns)
	h.routes["ListUsageProfiles"] = h.synthHandler(h.glue.ListUsageProfiles)
	h.routes["ModifyIntegration"] = h.synthHandler(h.glue.ModifyIntegration)
	h.routes["PutAsset"] = h.synthHandler(h.glue.PutAsset)
	h.routes["PutAssetType"] = h.synthHandler(h.glue.PutAssetType)
	h.routes["PutAttachment"] = h.synthHandler(h.glue.PutAttachment)
	h.routes["PutDataCatalogExportConfiguration"] = h.synthHandler(h.glue.PutDataCatalogExportConfiguration)
	h.routes["PutDataQualityProfileAnnotation"] = h.synthHandler(h.glue.PutDataQualityProfileAnnotation)
	h.routes["PutFormType"] = h.synthHandler(h.glue.PutFormType)
	h.routes["PutSchemaVersionMetadata"] = h.synthHandler(h.glue.PutSchemaVersionMetadata)
	h.routes["QuerySchemaVersionMetadata"] = h.synthHandler(h.glue.QuerySchemaVersionMetadata)
	h.routes["RegisterConnectionType"] = h.synthHandler(h.glue.RegisterConnectionType)
	h.routes["RemoveSchemaVersionMetadata"] = h.synthHandler(h.glue.RemoveSchemaVersionMetadata)
	h.routes["ResetJobBookmark"] = h.synthHandler(h.glue.ResetJobBookmark)
	h.routes["RunStatement"] = h.synthHandler(h.glue.RunStatement)
	h.routes["SearchAssets"] = h.synthHandler(h.glue.SearchAssets)
	h.routes["StartColumnStatisticsTaskRun"] = h.synthHandler(h.glue.StartColumnStatisticsTaskRun)
	h.routes["StartColumnStatisticsTaskRunSchedule"] = h.synthHandler(h.glue.StartColumnStatisticsTaskRunSchedule)
	h.routes["StartCrawlerSchedule"] = h.synthHandler(h.glue.StartCrawlerSchedule)
	h.routes["StartDataQualityRuleRecommendationRun"] = h.synthHandler(h.glue.StartDataQualityRuleRecommendationRun)
	h.routes["StartDataQualityRulesetEvaluationRun"] = h.synthHandler(h.glue.StartDataQualityRulesetEvaluationRun)
	h.routes["StartExportLabelsTaskRun"] = h.synthHandler(h.glue.StartExportLabelsTaskRun)
	h.routes["StartImportLabelsTaskRun"] = h.synthHandler(h.glue.StartImportLabelsTaskRun)
	h.routes["StartMaterializedViewRefreshTaskRun"] = h.synthHandler(h.glue.StartMaterializedViewRefreshTaskRun)
	h.routes["StartMLEvaluationTaskRun"] = h.synthHandler(h.glue.StartMLEvaluationTaskRun)
	h.routes["StartMLLabelingSetGenerationTaskRun"] = h.synthHandler(h.glue.StartMLLabelingSetGenerationTaskRun)
	h.routes["StopColumnStatisticsTaskRun"] = h.synthHandler(h.glue.StopColumnStatisticsTaskRun)
	h.routes["StopColumnStatisticsTaskRunSchedule"] = h.synthHandler(h.glue.StopColumnStatisticsTaskRunSchedule)
	h.routes["StopCrawlerSchedule"] = h.synthHandler(h.glue.StopCrawlerSchedule)
	h.routes["StopMaterializedViewRefreshTaskRun"] = h.synthHandler(h.glue.StopMaterializedViewRefreshTaskRun)
	h.routes["StopSession"] = h.synthHandler(h.glue.StopSession)
	h.routes["UpdateAsset"] = h.synthHandler(h.glue.UpdateAsset)
	h.routes["UpdateColumnStatisticsForPartition"] = h.synthHandler(h.glue.UpdateColumnStatisticsForPartition)
	h.routes["UpdateColumnStatisticsForTable"] = h.synthHandler(h.glue.UpdateColumnStatisticsForTable)
	h.routes["UpdateColumnStatisticsTaskSettings"] = h.synthHandler(h.glue.UpdateColumnStatisticsTaskSettings)
	h.routes["UpdateCrawlerSchedule"] = h.synthHandler(h.glue.UpdateCrawlerSchedule)
	h.routes["UpdateDataQualityRuleset"] = h.synthHandler(h.glue.UpdateDataQualityRuleset)
	h.routes["UpdateGlossary"] = h.synthHandler(h.glue.UpdateGlossary)
	h.routes["UpdateGlossaryTerm"] = h.synthHandler(h.glue.UpdateGlossaryTerm)
	h.routes["UpdateGlueIdentityCenterConfiguration"] = h.synthHandler(h.glue.UpdateGlueIdentityCenterConfiguration)
	h.routes["UpdateIntegrationResourceProperty"] = h.synthHandler(h.glue.UpdateIntegrationResourceProperty)
	h.routes["UpdateIntegrationTableProperties"] = h.synthHandler(h.glue.UpdateIntegrationTableProperties)
	h.routes["UpdateJobFromSourceControl"] = h.synthHandler(h.glue.UpdateJobFromSourceControl)
	h.routes["UpdateMLTransform"] = h.synthHandler(h.glue.UpdateMLTransform)
	h.routes["UpdateSourceControlFromJob"] = h.synthHandler(h.glue.UpdateSourceControlFromJob)
	h.routes["UpdateTableOptimizer"] = h.synthHandler(h.glue.UpdateTableOptimizer)
	h.routes["UpdateUsageProfile"] = h.synthHandler(h.glue.UpdateUsageProfile)
}
