package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/stackshy/cloudemu/v2/internal/compat"
)

const genNotice = "<!-- Generated by `go run ./internal/compatgen`. Do not edit by hand. -->\n\n"

// providerLabel is the human column label for each provider.
var providerLabel = map[string]string{ //nolint:gochecknoglobals // static display labels
	"aws":   "AWS",
	"azure": "Azure",
	"gcp":   "GCP",
}

// clientOrder fixes the order in which per-language summary rows are rendered.
// Only clients that actually have compat data for a service are shown, so
// languages without tests are omitted rather than reported as 0-of-N.
var clientOrder = []string{ //nolint:gochecknoglobals // fixed display order for per-language rows
	compat.ClientGoSDK, "sdkPython", "sdkJS", "sdkJava", "sdkDotnet",
}

// clientLabel is the human label for each known SDK/language client. Unknown
// clients fall back to their raw key.
var clientLabel = map[string]string{ //nolint:gochecknoglobals // static display labels
	compat.ClientGoSDK: "Go",
	"sdkPython":        "Python",
	"sdkJS":            "JavaScript",
	"sdkJava":          "Java",
	"sdkDotnet":        ".NET",
}

func renderReadme(entries []entry) string {
	var b strings.Builder

	b.WriteString(genNotice)
	b.WriteString("# Compatibility matrix\n\n")
	b.WriteString("Does a **real cloud SDK** call for each operation succeed against CloudEmu's ")
	b.WriteString("wire server? Every cell below is backed by a live round-trip through the ")
	b.WriteString("official SDK — not a hand-maintained checkbox.\n\n")
	b.WriteString("Legend: ✅ verified via a real SDK · `·` supported but not yet compat-tested · ")
	b.WriteString("`—` not offered by that provider.\n\n")
	b.WriteString("Each service's summary breaks the verified counts out per SDK/language. ")
	b.WriteString("Only languages with compat tests today appear; more rows land as their ")
	b.WriteString("suites are added.\n\n")

	for _, svc := range serviceOrder(entries) {
		renderService(&b, svc, entries)
	}

	return b.String()
}

func renderService(b *strings.Builder, service string, entries []entry) {
	rows := filterService(entries, service)
	provs := serviceProviders(rows)

	fmt.Fprintf(b, "## %s\n\n", service)

	// Header.
	b.WriteString("| Operation |")

	for _, p := range provs {
		fmt.Fprintf(b, " %s (%s) |", providerLabel[p], rows[0].Providers[p].Native)
	}

	b.WriteString("\n|---|")
	b.WriteString(strings.Repeat("---|", len(provs)))
	b.WriteString("\n")

	// Rows. counts[client][provider] holds verified operations per language.
	counts := map[string]map[string]int{}

	for _, e := range rows {
		fmt.Fprintf(b, "| %s |", e.Operation)

		for _, p := range provs {
			c, ok := e.Providers[p]
			sym := " · |"

			switch {
			case !ok:
				sym = " — |"
			case len(c.Clients) > 0:
				sym = " ✅ |"

				tally(counts, p, c.Clients)
			}

			b.WriteString(sym)
		}

		b.WriteString("\n")
	}

	b.WriteString("\n")
	renderSummary(b, service, provs, counts, len(rows))
}

// tally records each passing client for one provider cell.
func tally(counts map[string]map[string]int, provider string, clients map[string]string) {
	for client, status := range clients {
		if status != sdkPass {
			continue
		}

		if counts[client] == nil {
			counts[client] = map[string]int{}
		}

		counts[client][provider]++
	}
}

func renderSummary(b *strings.Builder, service string, provs []string, counts map[string]map[string]int, total int) {
	fmt.Fprintf(b, "**%s verified per language:**\n", service)

	for _, client := range orderedClients(counts) {
		perProv := counts[client]

		parts := make([]string, 0, len(provs))
		for _, p := range provs {
			parts = append(parts, fmt.Sprintf("%s %d/%d", providerLabel[p], perProv[p], total))
		}

		fmt.Fprintf(b, "- %s: %s\n", clientDisplay(client), strings.Join(parts, " · "))
	}

	b.WriteString("\n")
}

// orderedClients lists the clients that have data in counts: the known ones in
// clientOrder first, then any unknown client keys sorted alphabetically.
func orderedClients(counts map[string]map[string]int) []string {
	seen := map[string]bool{}
	ordered := make([]string, 0, len(counts))

	for _, client := range clientOrder {
		if _, ok := counts[client]; ok {
			ordered = append(ordered, client)
			seen[client] = true
		}
	}

	var extra []string

	for client := range counts {
		if !seen[client] {
			extra = append(extra, client)
		}
	}

	sort.Strings(extra)

	return append(ordered, extra...)
}

// clientDisplay is the human label for a client key, falling back to the key.
func clientDisplay(client string) string {
	if label, ok := clientLabel[client]; ok {
		return label
	}

	return client
}

func serviceOrder(entries []entry) []string {
	seen := map[string]bool{}
	order := []string{}

	for _, e := range entries {
		if !seen[e.Service] {
			seen[e.Service] = true

			order = append(order, e.Service)
		}
	}

	sort.Strings(order)

	return order
}

func filterService(entries []entry, service string) []entry {
	var rows []entry

	for _, e := range entries {
		if e.Service == service {
			rows = append(rows, e)
		}
	}

	return rows
}

// serviceProviders returns the providers that offer this service, in the fixed
// column order.
func serviceProviders(rows []entry) []string {
	present := map[string]bool{}

	for _, e := range rows {
		for p := range e.Providers {
			present[p] = true
		}
	}

	var provs []string

	for _, p := range providerOrder {
		if present[p] {
			provs = append(provs, p)
		}
	}

	return provs
}
