// Code generated by gcpenumgen. DO NOT EDIT.

package composer

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// environmentEnums maps each enum field of google.cloud.orchestration.airflow.service.v1.Environment, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var environmentEnums = gcpenum.Fields{
	"config.dataRetentionConfig.airflowMetadataRetentionConfig.retentionMode": {Type: "google.cloud.orchestration.airflow.service.v1.AirflowMetadataRetentionPolicyConfig.RetentionMode", Names: map[int32]string{
		0: "RETENTION_MODE_UNSPECIFIED",
		1: "RETENTION_MODE_ENABLED",
		2: "RETENTION_MODE_DISABLED",
	}},
	"config.dataRetentionConfig.taskLogsRetentionConfig.storageMode": {Type: "google.cloud.orchestration.airflow.service.v1.TaskLogsRetentionConfig.TaskLogsStorageMode", Names: map[int32]string{
		0: "TASK_LOGS_STORAGE_MODE_UNSPECIFIED",
		1: "CLOUD_LOGGING_AND_CLOUD_STORAGE",
		2: "CLOUD_LOGGING_ONLY",
	}},
	"config.environmentSize": {Type: "google.cloud.orchestration.airflow.service.v1.EnvironmentConfig.EnvironmentSize", Names: map[int32]string{
		0: "ENVIRONMENT_SIZE_UNSPECIFIED",
		1: "ENVIRONMENT_SIZE_SMALL",
		2: "ENVIRONMENT_SIZE_MEDIUM",
		3: "ENVIRONMENT_SIZE_LARGE",
	}},
	"config.privateEnvironmentConfig.networkingConfig.connectionType": {Type: "google.cloud.orchestration.airflow.service.v1.NetworkingConfig.ConnectionType", Names: map[int32]string{
		0: "CONNECTION_TYPE_UNSPECIFIED",
		1: "VPC_PEERING",
		2: "PRIVATE_SERVICE_CONNECT",
	}},
	"config.resilienceMode": {Type: "google.cloud.orchestration.airflow.service.v1.EnvironmentConfig.ResilienceMode", Names: map[int32]string{
		0: "RESILIENCE_MODE_UNSPECIFIED",
		1: "HIGH_RESILIENCE",
	}},
	"config.softwareConfig.webServerPluginsMode": {Type: "google.cloud.orchestration.airflow.service.v1.SoftwareConfig.WebServerPluginsMode", Names: map[int32]string{
		0: "WEB_SERVER_PLUGINS_MODE_UNSPECIFIED",
		1: "PLUGINS_DISABLED",
		2: "PLUGINS_ENABLED",
	}},
	"state": {Type: "google.cloud.orchestration.airflow.service.v1.Environment.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "RUNNING",
		3: "UPDATING",
		4: "DELETING",
		5: "ERROR",
	}},
}
