package managedgrafana_test

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stackshy/cloudemu/v2/config"
	"github.com/stackshy/cloudemu/v2/providers/azure/managedgrafana"
	managedgrafanasrv "github.com/stackshy/cloudemu/v2/server/azure/managedgrafana"
)

const (
	apiVer   = "?api-version=2023-09-01"
	basePath = "/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Dashboard/grafana/"
)

type wireResp struct {
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	Type     string            `json:"type"`
	Location string            `json:"location"`
	Tags     map[string]string `json:"tags"`
	Sku      *struct {
		Name string `json:"name"`
	} `json:"sku"`
	Identity *struct {
		Type        string `json:"type"`
		PrincipalID string `json:"principalId"`
		TenantID    string `json:"tenantId"`
	} `json:"identity"`
	Properties struct {
		ProvisioningState       string   `json:"provisioningState"`
		GrafanaVersion          string   `json:"grafanaVersion"`
		Endpoint                string   `json:"endpoint"`
		PublicNetworkAccess     string   `json:"publicNetworkAccess"`
		ZoneRedundancy          string   `json:"zoneRedundancy"`
		APIKey                  string   `json:"apiKey"`
		DeterministicOutboundIP string   `json:"deterministicOutboundIP"`
		OutboundIPs             []string `json:"outboundIPs"`
		DomainNameLabelScope    string   `json:"autoGeneratedDomainNameLabelScope"`
		GrafanaMajorVersion     string   `json:"grafanaMajorVersion"`
		GrafanaIntegrations     *struct {
			AzureMonitorWorkspaceIntegrations []struct {
				AzureMonitorWorkspaceResourceID string `json:"azureMonitorWorkspaceResourceId"`
			} `json:"azureMonitorWorkspaceIntegrations"`
		} `json:"grafanaIntegrations"`
	} `json:"properties"`
}

func newServer(t *testing.T) *httptest.Server {
	t.Helper()

	mock := managedgrafana.New(config.NewOptions())
	h := managedgrafanasrv.New(mock)
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)

	return srv
}

func do(t *testing.T, srv *httptest.Server, method, path, body string) (int, []byte) {
	t.Helper()

	var rdr io.Reader
	if body != "" {
		rdr = bytes.NewBufferString(body)
	}

	req, err := http.NewRequestWithContext(context.Background(), method, srv.URL+path, rdr)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}

	resp, err := srv.Client().Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, path, err)
	}
	defer func() { _ = resp.Body.Close() }()

	raw, _ := io.ReadAll(resp.Body)

	return resp.StatusCode, raw
}

func decode(t *testing.T, raw []byte) wireResp {
	t.Helper()

	var out wireResp
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("unmarshal: %v (%s)", err, raw)
	}

	return out
}

const createBody = `{
	"location": "West US",
	"tags": {"env": "dev"},
	"sku": {"name": "Standard"},
	"identity": {"type": "SystemAssigned"},
	"properties": {
		"grafanaMajorVersion": "10",
		"apiKey": "Enabled",
		"deterministicOutboundIP": "Enabled",
		"zoneRedundancy": "Enabled",
		"grafanaIntegrations": {
			"azureMonitorWorkspaceIntegrations": [
				{"azureMonitorWorkspaceResourceId": "/subscriptions/sub1/resourcegroups/rg1/providers/microsoft.monitor/accounts/amw1"}
			]
		}
	}
}`

func TestWireCreateAndComputedFields(t *testing.T) {
	srv := newServer(t)
	path := basePath + "graf1" + apiVer

	code, raw := do(t, srv, http.MethodPut, path, createBody)
	if code != http.StatusCreated {
		t.Fatalf("create status = %d, want 201 (%s)", code, raw)
	}

	got := decode(t, raw)
	if got.Type != "Microsoft.Dashboard/grafana" {
		t.Errorf("type = %q", got.Type)
	}

	if got.Location != "West US" {
		t.Errorf("location = %q, want West US", got.Location)
	}

	if got.Sku == nil || got.Sku.Name != "Standard" {
		t.Errorf("sku = %+v", got.Sku)
	}

	if got.Properties.Endpoint == "" || got.Properties.GrafanaVersion != "10.4.11" {
		t.Errorf("computed endpoint=%q version=%q", got.Properties.Endpoint, got.Properties.GrafanaVersion)
	}

	if got.Properties.ProvisioningState != "Succeeded" {
		t.Errorf("provisioningState = %q, want Succeeded", got.Properties.ProvisioningState)
	}

	if got.Properties.APIKey != "Enabled" || got.Properties.ZoneRedundancy != "Enabled" {
		t.Errorf("toggles apiKey=%q zr=%q", got.Properties.APIKey, got.Properties.ZoneRedundancy)
	}

	// deterministicOutboundIP Enabled → outboundIPs populated.
	if len(got.Properties.OutboundIPs) != 2 {
		t.Errorf("outboundIPs = %+v, want 2", got.Properties.OutboundIPs)
	}

	if got.Identity == nil || got.Identity.PrincipalID == "" || got.Identity.TenantID == "" {
		t.Errorf("identity ids = %+v", got.Identity)
	}

	if got.Properties.GrafanaIntegrations == nil ||
		len(got.Properties.GrafanaIntegrations.AzureMonitorWorkspaceIntegrations) != 1 {
		t.Errorf("grafanaIntegrations = %+v", got.Properties.GrafanaIntegrations)
	}
}

func TestWireGetIsByteStable(t *testing.T) {
	srv := newServer(t)
	path := basePath + "graf1" + apiVer

	if code, raw := do(t, srv, http.MethodPut, path, createBody); code != http.StatusCreated {
		t.Fatalf("create: %d (%s)", code, raw)
	}

	_, a := do(t, srv, http.MethodGet, path, "")
	_, b := do(t, srv, http.MethodGet, path, "")

	if !bytes.Equal(a, b) {
		t.Errorf("GET not byte-stable:\n a=%s\n b=%s", a, b)
	}
}

func TestWirePatchMergesAndPreservesComputed(t *testing.T) {
	srv := newServer(t)
	path := basePath + "graf1" + apiVer

	_, raw := do(t, srv, http.MethodPut, path, createBody)
	before := decode(t, raw)

	// PATCH mutates tags + one toggle. Everything else must survive.
	patch := `{"tags": {"env": "prod"}, "properties": {"publicNetworkAccess": "Disabled"}}`

	code, praw := do(t, srv, http.MethodPatch, path, patch)
	if code != http.StatusOK {
		t.Fatalf("patch status = %d (%s)", code, praw)
	}

	after := decode(t, praw)
	if after.Tags["env"] != "prod" || len(after.Tags) != 1 {
		t.Errorf("tags = %+v (want replaced)", after.Tags)
	}

	if after.Properties.PublicNetworkAccess != "Disabled" {
		t.Errorf("publicNetworkAccess = %q, want Disabled", after.Properties.PublicNetworkAccess)
	}

	// Untouched fields preserved.
	if after.Properties.APIKey != "Enabled" || after.Properties.GrafanaMajorVersion != "10" {
		t.Errorf("preserved fields drifted: apiKey=%q major=%q", after.Properties.APIKey, after.Properties.GrafanaMajorVersion)
	}

	if after.Properties.Endpoint != before.Properties.Endpoint ||
		after.Properties.GrafanaVersion != before.Properties.GrafanaVersion {
		t.Errorf("computed fields drifted on patch")
	}

	if after.Identity == nil || after.Identity.PrincipalID != before.Identity.PrincipalID {
		t.Errorf("identity drifted/wiped on patch: %+v", after.Identity)
	}

	if len(after.Properties.OutboundIPs) != 2 {
		t.Errorf("outboundIPs not preserved on patch: %+v", after.Properties.OutboundIPs)
	}
}

func TestWirePatchOnMissingIs404(t *testing.T) {
	srv := newServer(t)
	path := basePath + "nope" + apiVer

	if code, _ := do(t, srv, http.MethodPatch, path, `{"tags":{"a":"b"}}`); code != http.StatusNotFound {
		t.Errorf("patch missing = %d, want 404", code)
	}
}

func TestWireDeleteIdempotent(t *testing.T) {
	srv := newServer(t)
	path := basePath + "graf1" + apiVer

	do(t, srv, http.MethodPut, path, createBody)

	if code, _ := do(t, srv, http.MethodDelete, path, ""); code != http.StatusOK {
		t.Errorf("first delete = %d, want 200", code)
	}

	if code, _ := do(t, srv, http.MethodDelete, path, ""); code != http.StatusNoContent {
		t.Errorf("second delete = %d, want 204", code)
	}

	if code, _ := do(t, srv, http.MethodGet, path, ""); code != http.StatusNotFound {
		t.Errorf("get after delete = %d, want 404", code)
	}
}

func TestWireList(t *testing.T) {
	srv := newServer(t)

	for _, n := range []string{"a", "b"} {
		do(t, srv, http.MethodPut, basePath+n+apiVer, createBody)
	}

	code, raw := do(t, srv, http.MethodGet, basePath+apiVer, "")
	if code != http.StatusOK {
		t.Fatalf("list status = %d", code)
	}

	var out struct {
		Value []wireResp `json:"value"`
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("unmarshal list: %v", err)
	}

	if len(out.Value) != 2 {
		t.Errorf("list len = %d, want 2", len(out.Value))
	}
}

func TestWireMatches(t *testing.T) {
	h := managedgrafanasrv.New(managedgrafana.New(config.NewOptions()))

	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, basePath+"g1"+apiVer, nil)
	if !h.Matches(req) {
		t.Errorf("handler should match grafana path")
	}

	other, _ := http.NewRequestWithContext(context.Background(), http.MethodGet,
		"/subscriptions/s/resourceGroups/r/providers/Microsoft.Storage/storageAccounts/x"+apiVer, nil)
	if h.Matches(other) {
		t.Errorf("handler should not match storage path")
	}
}
