package managedgrafana

import (
	"encoding/json"

	"github.com/stackshy/cloudemu/v2/providers/azure/managedgrafana"
)

// grafanaRequest is the ARM PUT/PATCH body. location, tags, sku and identity are
// top-level; the remaining configuration lives under properties.
type grafanaRequest struct {
	Location   string             `json:"location,omitempty"`
	Tags       map[string]string  `json:"tags,omitempty"`
	Sku        *skuWire           `json:"sku,omitempty"`
	Identity   *identityRequest   `json:"identity,omitempty"`
	Properties *propertiesRequest `json:"properties,omitempty"`
}

// skuWire is the sku block on the wire. Only name (and the optional size) is
// writable.
type skuWire struct {
	Name string `json:"name"`
	Size string `json:"size,omitempty"`
}

// identityRequest is the writable half of the identity block; the minted ids are
// read-only. userAssignedIdentities is a map of ARM ids to (empty) objects on
// input.
type identityRequest struct {
	Type         string                     `json:"type"`
	UserAssigned map[string]json.RawMessage `json:"userAssignedIdentities,omitempty"`
}

// propertiesRequest is the writable subset of properties. Pointer fields let a
// PATCH overlay only what it names. autoGeneratedDomainNameLabelScope is consumed
// only at create (it is immutable).
type propertiesRequest struct {
	PublicNetworkAccess     *string             `json:"publicNetworkAccess,omitempty"`
	ZoneRedundancy          *string             `json:"zoneRedundancy,omitempty"`
	APIKey                  *string             `json:"apiKey,omitempty"`
	DeterministicOutboundIP *string             `json:"deterministicOutboundIP,omitempty"`
	DomainNameLabelScope    *string             `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	GrafanaMajorVersion     *string             `json:"grafanaMajorVersion,omitempty"`
	GrafanaIntegrations     *grafanaIntegration `json:"grafanaIntegrations,omitempty"`
}

// grafanaIntegration is the writable grafanaIntegrations block; only the Azure
// Monitor workspace integrations are modeled.
type grafanaIntegration struct {
	AzureMonitorWorkspaceIntegrations []monitorIntegration `json:"azureMonitorWorkspaceIntegrations"`
}

// monitorIntegration is one connected Azure Monitor workspace.
type monitorIntegration struct {
	AzureMonitorWorkspaceResourceID string `json:"azureMonitorWorkspaceResourceId"`
}

// grafanaResponse is the ARM representation of a grafana resource.
type grafanaResponse struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	Location   string             `json:"location"`
	Tags       map[string]string  `json:"tags,omitempty"`
	Sku        *skuWire           `json:"sku,omitempty"`
	Identity   *identityResponse  `json:"identity,omitempty"`
	Properties propertiesResponse `json:"properties"`
}

// identityResponse carries the identity block, including the service-minted ids.
type identityResponse struct {
	Type         string                         `json:"type"`
	PrincipalID  string                         `json:"principalId,omitempty"`
	TenantID     string                         `json:"tenantId,omitempty"`
	UserAssigned map[string]userAssignedWireVal `json:"userAssignedIdentities,omitempty"`
}

// userAssignedWireVal is the minted id pair for a user-assigned identity.
type userAssignedWireVal struct {
	PrincipalID string `json:"principalId"`
	ClientID    string `json:"clientId"`
}

// propertiesResponse is the properties block. The computed fields
// (provisioningState, grafanaVersion, endpoint, outboundIPs) are stable.
type propertiesResponse struct {
	ProvisioningState       string              `json:"provisioningState"`
	GrafanaVersion          string              `json:"grafanaVersion"`
	Endpoint                string              `json:"endpoint"`
	PublicNetworkAccess     string              `json:"publicNetworkAccess"`
	ZoneRedundancy          string              `json:"zoneRedundancy"`
	APIKey                  string              `json:"apiKey"`
	DeterministicOutboundIP string              `json:"deterministicOutboundIP"`
	OutboundIPs             []string            `json:"outboundIPs,omitempty"`
	DomainNameLabelScope    string              `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	GrafanaMajorVersion     string              `json:"grafanaMajorVersion"`
	GrafanaIntegrations     *grafanaIntegration `json:"grafanaIntegrations,omitempty"`
}

// listResponse is the ARM list envelope. nextLink is omitted — the emulator
// returns a single page.
type listResponse struct {
	Value []grafanaResponse `json:"value"`
}

// toResponse projects a stored resource onto its ARM wire representation.
func toResponse(s *managedgrafana.Grafana) grafanaResponse {
	return grafanaResponse{
		ID:         s.ARMID(),
		Name:       s.Name,
		Type:       armType,
		Location:   s.Location,
		Tags:       s.Tags,
		Sku:        toSkuWire(s.Sku),
		Identity:   toIdentityResponse(s.Identity),
		Properties: toPropertiesResponse(s),
	}
}

func toPropertiesResponse(s *managedgrafana.Grafana) propertiesResponse {
	return propertiesResponse{
		ProvisioningState:       s.ProvisioningState,
		GrafanaVersion:          s.GrafanaVersion,
		Endpoint:                s.Endpoint,
		PublicNetworkAccess:     s.PublicNetworkAccess,
		ZoneRedundancy:          s.ZoneRedundancy,
		APIKey:                  s.APIKey,
		DeterministicOutboundIP: s.DeterministicOutboundIP,
		OutboundIPs:             s.OutboundIPs,
		DomainNameLabelScope:    s.DomainNameLabelScope,
		GrafanaMajorVersion:     s.GrafanaMajorVersion,
		GrafanaIntegrations:     toIntegrationWire(s.MonitorWorkspaceIDs),
	}
}

func toSkuWire(in *managedgrafana.Sku) *skuWire {
	if in == nil {
		return nil
	}

	return &skuWire{Name: in.Name, Size: in.Size}
}

// toIntegrationWire projects stored Azure Monitor workspace ids onto the
// grafanaIntegrations block, returning nil when none are set.
func toIntegrationWire(ids []string) *grafanaIntegration {
	if len(ids) == 0 {
		return nil
	}

	out := &grafanaIntegration{AzureMonitorWorkspaceIntegrations: make([]monitorIntegration, 0, len(ids))}
	for _, id := range ids {
		out.AzureMonitorWorkspaceIntegrations = append(out.AzureMonitorWorkspaceIntegrations,
			monitorIntegration{AzureMonitorWorkspaceResourceID: id})
	}

	return out
}

func toIdentityResponse(in *managedgrafana.Identity) *identityResponse {
	if in == nil {
		return nil
	}

	out := &identityResponse{Type: in.Type, PrincipalID: in.PrincipalID, TenantID: in.TenantID}

	if len(in.UserAssigned) > 0 {
		out.UserAssigned = make(map[string]userAssignedWireVal, len(in.UserAssigned))
		for id, v := range in.UserAssigned {
			out.UserAssigned[id] = userAssignedWireVal{PrincipalID: v.PrincipalID, ClientID: v.ClientID}
		}
	}

	return out
}

// toDriverIdentity maps a wire identity request onto the driver identity. Only
// the type and the user-assigned id keys are carried; the mock mints the ids.
func toDriverIdentity(in *identityRequest) *managedgrafana.Identity {
	if in == nil {
		return nil
	}

	out := &managedgrafana.Identity{Type: in.Type}

	if len(in.UserAssigned) > 0 {
		out.UserAssigned = make(map[string]managedgrafana.UserAssignedValue, len(in.UserAssigned))
		for id := range in.UserAssigned {
			out.UserAssigned[id] = managedgrafana.UserAssignedValue{}
		}
	}

	return out
}

// toDriverSku maps a wire sku onto the driver sku.
func toDriverSku(in *skuWire) *managedgrafana.Sku {
	if in == nil {
		return nil
	}

	return &managedgrafana.Sku{Name: in.Name, Size: in.Size}
}

// integrationIDs flattens the grafanaIntegrations block into the workspace id
// list the driver stores.
func integrationIDs(in *grafanaIntegration) []string {
	if in == nil {
		return nil
	}

	out := make([]string, 0, len(in.AzureMonitorWorkspaceIntegrations))
	for _, m := range in.AzureMonitorWorkspaceIntegrations {
		out = append(out, m.AzureMonitorWorkspaceResourceID)
	}

	return out
}
