package guardduty

import (
	"context"
	"encoding/json"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/stackshy/cloudemu/v2/internal/idgen"
	"github.com/stackshy/cloudemu/v2/services/guardduty/driver"
)

// findingSchemaVersion is the finding schema version the emulator reports, matching
// the version real GuardDuty currently emits.
const findingSchemaVersion = "2.0"

// Representative severity scores per GuardDuty's LOW/MEDIUM/HIGH banding, used to
// give generated sample findings realistic severities.
const (
	severityHigh   = 8.0
	severityMedium = 5.0
	severityLow    = 2.0
)

// Finding field names shared by the wire representation, sort criteria, and
// finding-criteria filters.
const (
	fieldType       = "type"
	fieldSeverity   = "severity"
	fieldConfidence = "confidence"
	fieldUpdatedAt  = "updatedAt"
	fieldCreatedAt  = "createdAt"
)

// defaultSampleFindingTypes is the set generated by CreateSampleFindings when the
// caller does not request specific finding types.
func defaultSampleFindingTypes() []string {
	return []string{
		"Recon:EC2/PortProbeUnprotectedPort",
		"UnauthorizedAccess:EC2/SSHBruteForce",
		"Trojan:EC2/DNSDataExfiltration",
	}
}

// findingData is the server-side state of one finding under a detector. Timestamps
// are stored as time.Time and rendered as ISO strings on the wire so the emulator
// stays deterministic against the injected clock.
type findingData struct {
	id             string
	findingType    string
	severity       float64
	confidence     float64
	title          string
	description    string
	accountID      string
	region         string
	arn            string
	archived       bool
	count          int32
	resourceRole   string
	resourceType   string
	feedback       string
	comment        string
	createdAt      time.Time
	updatedAt      time.Time
	eventFirstSeen time.Time
	eventLastSeen  time.Time
}

// severityForFindingType maps a finding type prefix to a representative severity,
// mirroring GuardDuty's LOW/MEDIUM/HIGH banding so sample findings are realistic.
func severityForFindingType(ft string) float64 {
	switch {
	case strings.HasPrefix(ft, "Backdoor"), strings.HasPrefix(ft, "Trojan"),
		strings.HasPrefix(ft, "CryptoCurrency"):
		return severityHigh
	case strings.HasPrefix(ft, "UnauthorizedAccess"), strings.HasPrefix(ft, "Impact"):
		return severityMedium
	default:
		return severityLow
	}
}

// CreateSampleFindings generates one sample finding per requested finding type (or
// a default set when none are requested), stored under the detector keyed by a
// server-minted findingId.
func (m *Mock) CreateSampleFindings(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req struct {
		FindingTypes []string `json:"findingTypes"`
	}

	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	types := req.FindingTypes
	if len(types) == 0 {
		types = defaultSampleFindingTypes()
	}

	now := m.now()

	dd.mu.Lock()
	for _, ft := range types {
		fd := m.newSampleFinding(detectorID, ft, now)
		dd.findings[fd.id] = fd
	}
	dd.mu.Unlock()

	return json.Marshal(map[string]any{})
}

// newSampleFinding builds a finding for a single type. The findingId is
// server-minted so two sample-finding calls never collide.
func (m *Mock) newSampleFinding(detectorID, ft string, now time.Time) findingData {
	id := idgen.GenerateID("") + idgen.GenerateID("")

	return findingData{
		id:             id,
		findingType:    ft,
		severity:       severityForFindingType(ft),
		confidence:     5.0,
		title:          "Sample finding: " + ft,
		description:    "This is a sample finding generated by cloudemu for type " + ft + ".",
		accountID:      m.opts.AccountID,
		region:         m.opts.Region,
		arn:            m.findingARN(detectorID, id),
		count:          1,
		resourceRole:   "TARGET",
		resourceType:   "Instance",
		createdAt:      now,
		updatedAt:      now,
		eventFirstSeen: now,
		eventLastSeen:  now,
	}
}

// findingARN builds the ARN real GuardDuty reports for a finding.
func (m *Mock) findingARN(detectorID, findingID string) string {
	return idgen.AWSARN("guardduty", m.opts.Region, m.opts.AccountID,
		"detector/"+detectorID+"/finding/"+findingID)
}

// GetFindings returns the full finding objects for the requested IDs, deep-copied.
// Unknown IDs are silently omitted, matching real GuardDuty. The optional
// SortCriteria orders the result.
func (m *Mock) GetFindings(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req struct {
		FindingIDs   []string             `json:"findingIds"`
		SortCriteria *sortCriteriaRequest `json:"sortCriteria"`
	}

	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	dd.mu.RLock()
	found := make([]findingData, 0, len(req.FindingIDs))

	for _, id := range req.FindingIDs {
		if fd, ok := dd.findings[id]; ok {
			found = append(found, fd)
		}
	}
	dd.mu.RUnlock()

	sortFindings(found, req.SortCriteria)

	wire := make([]map[string]any, 0, len(found))
	for i := range found {
		wire = append(wire, m.findingToWire(detectorID, found[i]))
	}

	return json.Marshal(map[string]any{"findings": wire})
}

// ListFindings returns finding IDs honoring FindingCriteria, SortCriteria, and
// pagination. Per the GuardDuty API contract, when the criteria does not constrain
// service.archived, findings of both states are listed.
func (m *Mock) ListFindings(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req listFindingsRequest
	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	crit := parseCriteria(req.FindingCriteria)

	matched := m.matchingFindings(dd, crit)
	sortFindings(matched, req.SortCriteria)

	ids := make([]string, 0, len(matched))
	for i := range matched {
		ids = append(ids, matched[i].id)
	}

	page := driver.Page{NextToken: req.NextToken, MaxResults: int32Deref(req.MaxResults)}

	pageIDs, next, perr := paginateIDs(ids, page)
	if perr != nil {
		return nil, perr
	}

	if pageIDs == nil {
		pageIDs = []string{}
	}

	return json.Marshal(withNextToken(map[string]any{"findingIds": pageIDs}, next))
}

// matchingFindings snapshots the detector's findings that satisfy crit under the
// read lock, returning value copies safe to sort and read outside the lock.
func (*Mock) matchingFindings(dd *detectorData, crit []criterion) []findingData {
	dd.mu.RLock()
	defer dd.mu.RUnlock()

	out := make([]findingData, 0, len(dd.findings))

	for id := range dd.findings {
		fd := dd.findings[id]
		if matchesCriteria(fd, crit) {
			out = append(out, fd)
		}
	}

	return out
}

// ArchiveFindings sets Service.Archived=true on each requested finding under the
// detector lock. Unknown IDs are ignored.
func (m *Mock) ArchiveFindings(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	return m.setArchived(detectorID, body, true)
}

// UnarchiveFindings clears Service.Archived on each requested finding.
func (m *Mock) UnarchiveFindings(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	return m.setArchived(detectorID, body, false)
}

// setArchived flips the archived flag on the requested findings.
func (m *Mock) setArchived(detectorID string, body json.RawMessage, archived bool) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req struct {
		FindingIDs []string `json:"findingIds"`
	}

	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	now := m.now()

	dd.mu.Lock()
	for _, id := range req.FindingIDs {
		if fd, ok := dd.findings[id]; ok {
			fd.archived = archived
			fd.updatedAt = now
			dd.findings[id] = fd
		}
	}
	dd.mu.Unlock()

	return json.Marshal(map[string]any{})
}

// UpdateFindingsFeedback records USEFUL/NOT_USEFUL feedback and an optional comment
// on the requested findings.
func (m *Mock) UpdateFindingsFeedback(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req struct {
		FindingIDs []string `json:"findingIds"`
		Feedback   string   `json:"feedback"`
		Comments   string   `json:"comments"`
	}

	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	if req.Feedback != "USEFUL" && req.Feedback != "NOT_USEFUL" {
		return nil, badRequest("feedback must be USEFUL or NOT_USEFUL")
	}

	now := m.now()

	dd.mu.Lock()
	for _, id := range req.FindingIDs {
		if fd, ok := dd.findings[id]; ok {
			fd.feedback = req.Feedback
			fd.comment = req.Comments
			fd.updatedAt = now
			dd.findings[id] = fd
		}
	}
	dd.mu.Unlock()

	return json.Marshal(map[string]any{})
}

// getFindingsStatisticsRequest is the GetFindingsStatistics request body.
type getFindingsStatisticsRequest struct {
	FindingCriteria       *findingCriteriaRequest `json:"findingCriteria"`
	FindingStatisticTypes []string                `json:"findingStatisticTypes"`
	GroupBy               string                  `json:"groupBy"`
	OrderBy               string                  `json:"orderBy"`
}

// GetFindingsStatistics groups the detector's findings by the requested statistic
// type and/or GroupBy dimension, returning the FindingStatistics wire shape.
func (m *Mock) GetFindingsStatistics(_ context.Context, detectorID string, body json.RawMessage) (json.RawMessage, error) {
	dd, err := m.getDetector(detectorID)
	if err != nil {
		return nil, err
	}

	var req getFindingsStatisticsRequest
	if uerr := unmarshalBody(body, &req); uerr != nil {
		return nil, uerr
	}

	crit := parseCriteria(req.FindingCriteria)

	matched := m.matchingFindings(dd, crit)
	stats := findingStatistics(matched, req)

	return json.Marshal(map[string]any{"findingStatistics": stats})
}

// findingStatistics builds the FindingStatistics response for the matched findings
// per the request's statistic types and GroupBy dimension.
func findingStatistics(fs []findingData, req getFindingsStatisticsRequest) map[string]any {
	stats := map[string]any{}

	if contains(req.FindingStatisticTypes, "COUNT_BY_SEVERITY") {
		stats["countBySeverity"] = countBySeverity(fs)
	}

	switch strings.ToUpper(req.GroupBy) {
	case "SEVERITY":
		stats["groupedBySeverity"] = groupedBySeverity(fs)
	case "FINDING_TYPE":
		stats["groupedByFindingType"] = groupedByFindingType(fs)
	}

	return stats
}

// countBySeverity returns the deprecated CountBySeverity map (severity label→count).
func countBySeverity(fs []findingData) map[string]int32 {
	out := map[string]int32{}

	for i := range fs {
		out[severityLabel(fs[i].severity)]++
	}

	return out
}

// severityLabel renders a severity score the way the CountBySeverity map keys it.
func severityLabel(sev float64) string {
	return strconv.FormatFloat(sev, 'f', -1, 64)
}

// groupedBySeverity returns the SeverityStatistics list, one entry per distinct
// severity, ordered ascending by severity for determinism.
func groupedBySeverity(fs []findingData) []map[string]any {
	type agg struct {
		total int32
		last  time.Time
	}

	byS := map[float64]*agg{}

	for i := range fs {
		a := byS[fs[i].severity]
		if a == nil {
			a = &agg{}
			byS[fs[i].severity] = a
		}

		a.total++
		if fs[i].updatedAt.After(a.last) {
			a.last = fs[i].updatedAt
		}
	}

	sevs := make([]float64, 0, len(byS))
	for s := range byS {
		sevs = append(sevs, s)
	}

	sort.Float64s(sevs)

	out := make([]map[string]any, 0, len(sevs))
	for _, s := range sevs {
		out = append(out, map[string]any{
			fieldSeverity:     s,
			"totalFindings":   byS[s].total,
			"lastGeneratedAt": byS[s].last.UTC().Unix(),
		})
	}

	return out
}

// groupedByFindingType returns the FindingTypeStatistics list, one entry per
// distinct finding type, ordered by type name for determinism.
func groupedByFindingType(fs []findingData) []map[string]any {
	total := map[string]int32{}
	last := map[string]time.Time{}

	for i := range fs {
		ft := fs[i].findingType
		total[ft]++

		if fs[i].updatedAt.After(last[ft]) {
			last[ft] = fs[i].updatedAt
		}
	}

	types := make([]string, 0, len(total))
	for t := range total {
		types = append(types, t)
	}

	sort.Strings(types)

	out := make([]map[string]any, 0, len(types))
	for _, t := range types {
		out = append(out, map[string]any{
			"findingType":     t,
			"totalFindings":   total[t],
			"lastGeneratedAt": last[t].UTC().Unix(),
		})
	}

	return out
}

// findingToWire renders a stored finding as the REST-JSON object real GuardDuty
// returns from GetFindings. Every value is copied from the value receiver, so the
// result never aliases stored state.
//
//nolint:gocritic // hugeParam: taken by value to snapshot a copy of stored state.
func (*Mock) findingToWire(detectorID string, fd findingData) map[string]any {
	service := map[string]any{
		"archived":       fd.archived,
		"count":          fd.count,
		"detectorId":     detectorID,
		"eventFirstSeen": isoFinding(fd.eventFirstSeen),
		"eventLastSeen":  isoFinding(fd.eventLastSeen),
		"resourceRole":   fd.resourceRole,
		"serviceName":    "guardduty",
		"additionalInfo": map[string]any{"sample": "true"},
	}

	if fd.feedback != "" {
		service["userFeedback"] = fd.feedback
	}

	return map[string]any{
		"id":            fd.id,
		"arn":           fd.arn,
		"schemaVersion": findingSchemaVersion,
		"accountId":     fd.accountID,
		"region":        fd.region,
		fieldType:       fd.findingType,
		fieldSeverity:   fd.severity,
		fieldConfidence: fd.confidence,
		"title":         fd.title,
		"description":   fd.description,
		fieldCreatedAt:  isoFinding(fd.createdAt),
		fieldUpdatedAt:  isoFinding(fd.updatedAt),
		"service":       service,
		"resource":      map[string]any{"resourceType": fd.resourceType},
	}
}

// isoFinding renders a timestamp in the layout GuardDuty uses for finding
// createdAt/updatedAt/eventFirstSeen/eventLastSeen string fields.
func isoFinding(t time.Time) string {
	return t.UTC().Format(isoTimestamp)
}

// sortCriteriaRequest is the shared SortCriteria request shape.
type sortCriteriaRequest struct {
	AttributeName string `json:"attributeName"`
	OrderBy       string `json:"orderBy"`
}

// listFindingsRequest is the ListFindings request body.
type listFindingsRequest struct {
	FindingCriteria *findingCriteriaRequest `json:"findingCriteria"`
	SortCriteria    *sortCriteriaRequest    `json:"sortCriteria"`
	MaxResults      *int32                  `json:"maxResults"`
	NextToken       string                  `json:"nextToken"`
}

// findingCriteriaRequest is the FindingCriteria request body.
type findingCriteriaRequest struct {
	Criterion map[string]conditionRequest `json:"criterion"`
}

// conditionRequest models the FindingCriteria Condition operators. Both the modern
// and deprecated operator spellings are honored so any SDK version matches.
type conditionRequest struct {
	Eq                 []string `json:"eq"`
	Neq                []string `json:"neq"`
	Equals             []string `json:"equals"`
	NotEquals          []string `json:"notEquals"`
	Gt                 *int64   `json:"gt"`
	Gte                *int64   `json:"gte"`
	Lt                 *int64   `json:"lt"`
	Lte                *int64   `json:"lte"`
	GreaterThan        *int64   `json:"greaterThan"`
	GreaterThanOrEqual *int64   `json:"greaterThanOrEqual"`
	LessThan           *int64   `json:"lessThan"`
	LessThanOrEqual    *int64   `json:"lessThanOrEqual"`
}

// criterion is a normalized, evaluated finding filter over a single field.
type criterion struct {
	field     string
	eq        []string
	neq       []string
	gt        *int64
	gte       *int64
	lt        *int64
	lte       *int64
	numeric   bool // true when any numeric operator is present.
	archivedC bool // true when the field is service.archived.
}

// parseCriteria normalizes a FindingCriteria request into evaluated criteria. It
// returns nil when there is no criteria (match everything).
func parseCriteria(req *findingCriteriaRequest) []criterion {
	if req == nil || len(req.Criterion) == 0 {
		return nil
	}

	out := make([]criterion, 0, len(req.Criterion))

	for field := range req.Criterion {
		c := req.Criterion[field]
		cr := criterion{
			field:     field,
			eq:        firstNonEmpty(c.Equals, c.Eq),
			neq:       firstNonEmpty(c.NotEquals, c.Neq),
			gt:        firstNonNil(c.GreaterThan, c.Gt),
			gte:       firstNonNil(c.GreaterThanOrEqual, c.Gte),
			lt:        firstNonNil(c.LessThan, c.Lt),
			lte:       firstNonNil(c.LessThanOrEqual, c.Lte),
			archivedC: field == "service.archived",
		}
		cr.numeric = cr.gt != nil || cr.gte != nil || cr.lt != nil || cr.lte != nil
		out = append(out, cr)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].field < out[j].field })

	return out
}

// matchesCriteria reports whether a finding satisfies every criterion (AND). When
// no criterion constrains service.archived, findings of both states qualify.
//
//nolint:gocritic // hugeParam: read-only value passed through the match helpers.
func matchesCriteria(fd findingData, crit []criterion) bool {
	for i := range crit {
		if !matchesOne(fd, crit[i]) {
			return false
		}
	}

	return true
}

// matchesOne evaluates a single criterion against a finding.
//
//nolint:gocritic // hugeParam: read-only values passed through the match helpers.
func matchesOne(fd findingData, c criterion) bool {
	if c.archivedC {
		return matchArchived(fd, c)
	}

	if c.numeric {
		return matchNumeric(fieldNumber(fd, c.field), c)
	}

	return matchString(fieldString(fd, c.field), c)
}

// matchArchived matches the boolean service.archived field expressed as "true"/"false".
//
//nolint:gocritic // hugeParam: read-only values passed through the match helpers.
func matchArchived(fd findingData, c criterion) bool {
	got := strconv.FormatBool(fd.archived)

	return matchString(got, c)
}

// matchString applies the eq/neq operators to a string field value.
//
//nolint:gocritic // hugeParam: read-only criterion passed through the match helpers.
func matchString(got string, c criterion) bool {
	if len(c.eq) > 0 && !contains(c.eq, got) {
		return false
	}

	if len(c.neq) > 0 && contains(c.neq, got) {
		return false
	}

	return true
}

// matchNumeric applies the gt/gte/lt/lte operators to a numeric field value.
//
//nolint:gocritic // hugeParam: read-only criterion passed through the match helpers.
func matchNumeric(got int64, c criterion) bool {
	if c.gt != nil && !(got > *c.gt) {
		return false
	}

	if c.gte != nil && !(got >= *c.gte) {
		return false
	}

	if c.lt != nil && !(got < *c.lt) {
		return false
	}

	if c.lte != nil && !(got <= *c.lte) {
		return false
	}

	return true
}

// fieldString returns the string value of a supported finding field.
//
//nolint:gocritic // hugeParam: read-only finding read for a single field.
func fieldString(fd findingData, field string) string {
	switch field {
	case "id":
		return fd.id
	case fieldType:
		return fd.findingType
	case "accountId":
		return fd.accountID
	case "region":
		return fd.region
	case fieldSeverity:
		return strconv.FormatFloat(fd.severity, 'f', -1, 64)
	default:
		return ""
	}
}

// fieldNumber returns the numeric value of a supported finding field. severity is
// truncated to an integer and updatedAt is Unix-epoch milliseconds, matching the
// GuardDuty timestamp criteria contract.
//
//nolint:gocritic // hugeParam: read-only finding read for a single field.
func fieldNumber(fd findingData, field string) int64 {
	switch field {
	case fieldSeverity:
		return int64(fd.severity)
	case fieldConfidence:
		return int64(fd.confidence)
	case fieldUpdatedAt:
		return fd.updatedAt.UTC().UnixMilli()
	case fieldCreatedAt:
		return fd.createdAt.UTC().UnixMilli()
	default:
		return 0
	}
}

// sortFindings orders findings by the requested attribute (default updatedAt) and
// direction (default ascending), then by id to make ties deterministic.
func sortFindings(fs []findingData, sc *sortCriteriaRequest) {
	attr := fieldUpdatedAt
	desc := false

	if sc != nil {
		if sc.AttributeName != "" {
			attr = sc.AttributeName
		}

		desc = strings.EqualFold(sc.OrderBy, "DESC")
	}

	sort.SliceStable(fs, func(i, j int) bool {
		less := findingLess(fs[i], fs[j], attr)

		if desc {
			return findingLess(fs[j], fs[i], attr)
		}

		return less
	})
}

// findingLess reports whether a sorts before b by the given attribute, breaking
// ties on id for determinism.
//
//nolint:gocritic // hugeParam: read-only values compared during sort.
func findingLess(a, b findingData, attr string) bool {
	switch attr {
	case fieldSeverity:
		if a.severity != b.severity {
			return a.severity < b.severity
		}
	case fieldConfidence:
		if a.confidence != b.confidence {
			return a.confidence < b.confidence
		}
	case fieldCreatedAt:
		if !a.createdAt.Equal(b.createdAt) {
			return a.createdAt.Before(b.createdAt)
		}
	case fieldType:
		if a.findingType != b.findingType {
			return a.findingType < b.findingType
		}
	default:
		if !a.updatedAt.Equal(b.updatedAt) {
			return a.updatedAt.Before(b.updatedAt)
		}
	}

	return a.id < b.id
}

// int32Deref returns the value of p or 0 when nil.
func int32Deref(p *int32) int32 {
	if p == nil {
		return 0
	}

	return *p
}

// firstNonEmpty returns a if non-empty, else b.
func firstNonEmpty(a, b []string) []string {
	if len(a) > 0 {
		return a
	}

	return b
}

// firstNonNil returns a if non-nil, else b.
func firstNonNil(a, b *int64) *int64 {
	if a != nil {
		return a
	}

	return b
}

// contains reports whether s is in list.
func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}

	return false
}
