// Code generated by gcpenumgen. DO NOT EDIT.

package cloudfunctions

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// gen1FunctionEnums maps each enum field of google.cloud.functions.v1.CloudFunction, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var gen1FunctionEnums = gcpenum.Fields{
	"dockerRegistry": {Type: "google.cloud.functions.v1.CloudFunction.DockerRegistry", Names: map[int32]string{
		0: "DOCKER_REGISTRY_UNSPECIFIED",
		1: "CONTAINER_REGISTRY",
		2: "ARTIFACT_REGISTRY",
	}},
	"httpsTrigger.securityLevel": {Type: "google.cloud.functions.v1.HttpsTrigger.SecurityLevel", Names: map[int32]string{
		0: "SECURITY_LEVEL_UNSPECIFIED",
		1: "SECURE_ALWAYS",
		2: "SECURE_OPTIONAL",
	}},
	"ingressSettings": {Type: "google.cloud.functions.v1.CloudFunction.IngressSettings", Names: map[int32]string{
		0: "INGRESS_SETTINGS_UNSPECIFIED",
		1: "ALLOW_ALL",
		2: "ALLOW_INTERNAL_ONLY",
		3: "ALLOW_INTERNAL_AND_GCLB",
	}},
	"status": {Type: "google.cloud.functions.v1.CloudFunctionStatus", Names: map[int32]string{
		0: "CLOUD_FUNCTION_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "OFFLINE",
		3: "DEPLOY_IN_PROGRESS",
		4: "DELETE_IN_PROGRESS",
		5: "UNKNOWN",
	}},
	"vpcConnectorEgressSettings": {Type: "google.cloud.functions.v1.CloudFunction.VpcConnectorEgressSettings", Names: map[int32]string{
		0: "VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED",
		1: "PRIVATE_RANGES_ONLY",
		2: "ALL_TRAFFIC",
	}},
}

// gen2FunctionEnums maps each enum field of google.cloud.functions.v2.Function, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var gen2FunctionEnums = gcpenum.Fields{
	"buildConfig.dockerRegistry": {Type: "google.cloud.functions.v2.BuildConfig.DockerRegistry", Names: map[int32]string{
		0: "DOCKER_REGISTRY_UNSPECIFIED",
		1: "CONTAINER_REGISTRY",
		2: "ARTIFACT_REGISTRY",
	}},
	"environment": {Type: "google.cloud.functions.v2.Environment", Names: map[int32]string{
		0: "ENVIRONMENT_UNSPECIFIED",
		1: "GEN_1",
		2: "GEN_2",
	}},
	"eventTrigger.retryPolicy": {Type: "google.cloud.functions.v2.EventTrigger.RetryPolicy", Names: map[int32]string{
		0: "RETRY_POLICY_UNSPECIFIED",
		1: "RETRY_POLICY_DO_NOT_RETRY",
		2: "RETRY_POLICY_RETRY",
	}},
	"serviceConfig.ingressSettings": {Type: "google.cloud.functions.v2.ServiceConfig.IngressSettings", Names: map[int32]string{
		0: "INGRESS_SETTINGS_UNSPECIFIED",
		1: "ALLOW_ALL",
		2: "ALLOW_INTERNAL_ONLY",
		3: "ALLOW_INTERNAL_AND_GCLB",
	}},
	"serviceConfig.securityLevel": {Type: "google.cloud.functions.v2.ServiceConfig.SecurityLevel", Names: map[int32]string{
		0: "SECURITY_LEVEL_UNSPECIFIED",
		1: "SECURE_ALWAYS",
		2: "SECURE_OPTIONAL",
	}},
	"serviceConfig.vpcConnectorEgressSettings": {Type: "google.cloud.functions.v2.ServiceConfig.VpcConnectorEgressSettings", Names: map[int32]string{
		0: "VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED",
		1: "PRIVATE_RANGES_ONLY",
		2: "ALL_TRAFFIC",
	}},
	"state": {Type: "google.cloud.functions.v2.Function.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "FAILED",
		3: "DEPLOYING",
		4: "DELETING",
		5: "UNKNOWN",
	}},
	"stateMessages.severity": {Type: "google.cloud.functions.v2.StateMessage.Severity", Names: map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "ERROR",
		2: "WARNING",
		3: "INFO",
	}},
}
