// Code generated by gcpenumgen. DO NOT EDIT.

package artifactregistry

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// repositoryEnums maps each enum field of google.devtools.artifactregistry.v1.Repository, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var repositoryEnums = gcpenum.Fields{
	"cleanupPolicies.*.action": {Type: "google.devtools.artifactregistry.v1.CleanupPolicy.Action", Names: map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "DELETE",
		2: "KEEP",
	}},
	"cleanupPolicies.*.condition.tagState": {Type: "google.devtools.artifactregistry.v1.CleanupPolicyCondition.TagState", Names: map[int32]string{
		0: "TAG_STATE_UNSPECIFIED",
		1: "TAGGED",
		2: "UNTAGGED",
		3: "ANY",
	}},
	"format": {Type: "google.devtools.artifactregistry.v1.Repository.Format", Names: map[int32]string{
		0:  "FORMAT_UNSPECIFIED",
		1:  "DOCKER",
		2:  "MAVEN",
		3:  "NPM",
		5:  "APT",
		6:  "YUM",
		8:  "PYTHON",
		9:  "KFP",
		10: "GO",
		11: "GENERIC",
		12: "RUBY",
	}},
	"mavenConfig.versionPolicy": {Type: "google.devtools.artifactregistry.v1.Repository.MavenRepositoryConfig.VersionPolicy", Names: map[int32]string{
		0: "VERSION_POLICY_UNSPECIFIED",
		1: "RELEASE",
		2: "SNAPSHOT",
	}},
	"mode": {Type: "google.devtools.artifactregistry.v1.Repository.Mode", Names: map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "STANDARD_REPOSITORY",
		2: "VIRTUAL_REPOSITORY",
		3: "REMOTE_REPOSITORY",
	}},
	"remoteRepositoryConfig.aptRepository.publicRepository.repositoryBase": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase", Names: map[int32]string{
		0: "REPOSITORY_BASE_UNSPECIFIED",
		1: "DEBIAN",
		2: "UBUNTU",
		3: "DEBIAN_SNAPSHOT",
	}},
	"remoteRepositoryConfig.dockerRepository.publicRepository": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.DockerRepository.PublicRepository", Names: map[int32]string{
		0: "PUBLIC_REPOSITORY_UNSPECIFIED",
		1: "DOCKER_HUB",
	}},
	"remoteRepositoryConfig.mavenRepository.publicRepository": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.MavenRepository.PublicRepository", Names: map[int32]string{
		0: "PUBLIC_REPOSITORY_UNSPECIFIED",
		1: "MAVEN_CENTRAL",
	}},
	"remoteRepositoryConfig.npmRepository.publicRepository": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.NpmRepository.PublicRepository", Names: map[int32]string{
		0: "PUBLIC_REPOSITORY_UNSPECIFIED",
		1: "NPMJS",
	}},
	"remoteRepositoryConfig.pythonRepository.publicRepository": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.PythonRepository.PublicRepository", Names: map[int32]string{
		0: "PUBLIC_REPOSITORY_UNSPECIFIED",
		1: "PYPI",
	}},
	"remoteRepositoryConfig.yumRepository.publicRepository.repositoryBase": {Type: "google.devtools.artifactregistry.v1.RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase", Names: map[int32]string{
		0: "REPOSITORY_BASE_UNSPECIFIED",
		1: "CENTOS",
		2: "CENTOS_DEBUG",
		3: "CENTOS_VAULT",
		4: "CENTOS_STREAM",
		5: "ROCKY",
		6: "EPEL",
	}},
	"vulnerabilityScanningConfig.enablementConfig": {Type: "google.devtools.artifactregistry.v1.Repository.VulnerabilityScanningConfig.EnablementConfig", Names: map[int32]string{
		0: "ENABLEMENT_CONFIG_UNSPECIFIED",
		1: "INHERITED",
		2: "DISABLED",
	}},
	"vulnerabilityScanningConfig.enablementState": {Type: "google.devtools.artifactregistry.v1.Repository.VulnerabilityScanningConfig.EnablementState", Names: map[int32]string{
		0: "ENABLEMENT_STATE_UNSPECIFIED",
		1: "SCANNING_UNSUPPORTED",
		2: "SCANNING_DISABLED",
		3: "SCANNING_ACTIVE",
	}},
}
