// Code generated by gcpenumgen. DO NOT EDIT.

package memorystore

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// instanceEnums maps each enum field of google.cloud.redis.v1.Instance, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var instanceEnums = gcpenum.Fields{
	"connectMode": {Type: "google.cloud.redis.v1.Instance.ConnectMode", Names: map[int32]string{
		0: "CONNECT_MODE_UNSPECIFIED",
		1: "DIRECT_PEERING",
		2: "PRIVATE_SERVICE_ACCESS",
	}},
	"maintenancePolicy.weeklyMaintenanceWindow.day": {Type: "google.type.DayOfWeek", Names: map[int32]string{
		0: "DAY_OF_WEEK_UNSPECIFIED",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
	}},
	"persistenceConfig.persistenceMode": {Type: "google.cloud.redis.v1.PersistenceConfig.PersistenceMode", Names: map[int32]string{
		0: "PERSISTENCE_MODE_UNSPECIFIED",
		1: "DISABLED",
		2: "RDB",
	}},
	"persistenceConfig.rdbSnapshotPeriod": {Type: "google.cloud.redis.v1.PersistenceConfig.SnapshotPeriod", Names: map[int32]string{
		0: "SNAPSHOT_PERIOD_UNSPECIFIED",
		3: "ONE_HOUR",
		4: "SIX_HOURS",
		5: "TWELVE_HOURS",
		6: "TWENTY_FOUR_HOURS",
	}},
	"readReplicasMode": {Type: "google.cloud.redis.v1.Instance.ReadReplicasMode", Names: map[int32]string{
		0: "READ_REPLICAS_MODE_UNSPECIFIED",
		1: "READ_REPLICAS_DISABLED",
		2: "READ_REPLICAS_ENABLED",
	}},
	"state": {Type: "google.cloud.redis.v1.Instance.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "READY",
		3: "UPDATING",
		4: "DELETING",
		5: "REPAIRING",
		6: "MAINTENANCE",
		8: "IMPORTING",
		9: "FAILING_OVER",
	}},
	"suspensionReasons": {Type: "google.cloud.redis.v1.Instance.SuspensionReason", Names: map[int32]string{
		0: "SUSPENSION_REASON_UNSPECIFIED",
		1: "CUSTOMER_MANAGED_KEY_ISSUE",
	}},
	"tier": {Type: "google.cloud.redis.v1.Instance.Tier", Names: map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "BASIC",
		3: "STANDARD_HA",
	}},
	"transitEncryptionMode": {Type: "google.cloud.redis.v1.Instance.TransitEncryptionMode", Names: map[int32]string{
		0: "TRANSIT_ENCRYPTION_MODE_UNSPECIFIED",
		1: "SERVER_AUTHENTICATION",
		2: "DISABLED",
	}},
}
