// Code generated by gcpenumgen. DO NOT EDIT.

package backupdr

import "github.com/stackshy/cloudemu/v2/server/wire/gcpenum"

// vaultEnums maps each enum field of google.cloud.backupdr.v1.BackupVault, by JSON path, to its proto enum.
//
//nolint:gochecknoglobals // generated immutable proto enum table
var vaultEnums = gcpenum.Fields{
	"accessRestriction": {Type: "google.cloud.backupdr.v1.BackupVault.AccessRestriction", Names: map[int32]string{
		0: "ACCESS_RESTRICTION_UNSPECIFIED",
		1: "WITHIN_PROJECT",
		2: "WITHIN_ORGANIZATION",
		3: "UNRESTRICTED",
		4: "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA",
	}},
	"backupRetentionInheritance": {Type: "google.cloud.backupdr.v1.BackupVault.BackupRetentionInheritance", Names: map[int32]string{
		0: "BACKUP_RETENTION_INHERITANCE_UNSPECIFIED",
		1: "INHERIT_VAULT_RETENTION",
		2: "MATCH_BACKUP_EXPIRE_TIME",
	}},
	"state": {Type: "google.cloud.backupdr.v1.BackupVault.State", Names: map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "ACTIVE",
		3: "DELETING",
		4: "ERROR",
		5: "UPDATING",
	}},
}
