package frontdoor

// Azure ARM JSON wire structures and constants for Microsoft.Cdn/profiles and its
// afdEndpoints / originGroups child types. Only the shell fields that live outside
// the "properties" object (location, sku, kind, identity, tags) are typed; the
// properties themselves are carried as generic JSON so nested values — including
// explicit zeros in loadBalancingSettings — round-trip verbatim.

const (
	providerName = "Microsoft.Cdn"

	typeProfiles      = "profiles"
	subTypeEndpoints  = "afdEndpoints"
	subTypeOrigGroups = "originGroups"

	profileResourceType  = "Microsoft.Cdn/profiles"
	endpointResourceType = "Microsoft.Cdn/profiles/afdEndpoints"
	origGroupResType     = "Microsoft.Cdn/profiles/originGroups"

	// kindFrontDoor is stamped on every profile so the portal (and Terraform)
	// distinguishes a Standard/Premium Front Door from a classic CDN profile.
	kindFrontDoor = "frontdoor"

	// defaultLocation is the location Front Door resources use; Terraform sends
	// "global" but the resource is region-agnostic.
	defaultLocation = "global"

	// Terminal computed stamps the SDK poller / Terraform wait for.
	provisioningStateSucceeded = "Succeeded"
	resourceStateActive        = "Active"
	deploymentStatusNotStarted = "NotStarted"

	// Property keys.
	provisioningStateKey     = "provisioningState"
	resourceStateKey         = "resourceState"
	frontDoorIDKey           = "frontDoorId"
	originResponseTimeoutKey = "originResponseTimeoutSeconds"
	hostNameKey              = "hostName"
	deploymentStatusKey      = "deploymentStatus"
	enabledStateKey          = "enabledState"
	autoGenDomainScopeKey    = "autoGeneratedDomainNameLabelScope"

	// Defaults injected when the request omits them.
	originResponseTimeoutDefault = 30
	enabledStateDefault          = "Enabled"
	autoGenDomainScopeDefault    = "TenantReuse"

	// hostNameSuffix is the Front Door endpoint domain suffix. The full hostName is
	// "<endpoint>-<token>.z01.azurefd.net".
	hostNameSuffix   = ".z01.azurefd.net"
	hostNameTokenLen = 10
)

// skuJSON is the top-level Front Door profile sku ({name}).
type skuJSON struct {
	Name string `json:"name,omitempty"`
}

// profileJSON is the ARM Microsoft.Cdn/profiles wire body. Sku, location, kind and
// identity are top-level (the server-wide echo cannot reach them); properties is
// generic so the computed frontDoorId/provisioningState and every deferred property
// coexist in one object.
type profileJSON struct {
	ID         string            `json:"id,omitempty"`
	Name       string            `json:"name,omitempty"`
	Type       string            `json:"type,omitempty"`
	Location   string            `json:"location,omitempty"`
	SKU        *skuJSON          `json:"sku,omitempty"`
	Kind       string            `json:"kind,omitempty"`
	Identity   map[string]any    `json:"identity,omitempty"`
	Etag       string            `json:"etag,omitempty"`
	Tags       map[string]string `json:"tags,omitempty"`
	Properties map[string]any    `json:"properties,omitempty"`
}

// endpointJSON is the ARM afdEndpoints wire body. Location and tags are top-level;
// properties carries enabledState/autoGeneratedDomainNameLabelScope and the
// computed hostName.
type endpointJSON struct {
	ID         string            `json:"id,omitempty"`
	Name       string            `json:"name,omitempty"`
	Type       string            `json:"type,omitempty"`
	Location   string            `json:"location,omitempty"`
	Etag       string            `json:"etag,omitempty"`
	Tags       map[string]string `json:"tags,omitempty"`
	Properties map[string]any    `json:"properties,omitempty"`
}

// origGroupJSON is the ARM originGroups wire body. It has no location and no tags;
// properties carries loadBalancingSettings/healthProbeSettings verbatim.
type origGroupJSON struct {
	ID         string         `json:"id,omitempty"`
	Name       string         `json:"name,omitempty"`
	Type       string         `json:"type,omitempty"`
	Etag       string         `json:"etag,omitempty"`
	Properties map[string]any `json:"properties,omitempty"`
}

// profileListResult is the ARM list envelope for profiles.
type profileListResult struct {
	Value []profileJSON `json:"value"`
}

// endpointListResult is the ARM list envelope for afdEndpoints.
type endpointListResult struct {
	Value []endpointJSON `json:"value"`
}

// origGroupListResult is the ARM list envelope for originGroups.
type origGroupListResult struct {
	Value []origGroupJSON `json:"value"`
}
